import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, BookOpen } from "lucide-react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SEO } from "@/components/SEO";
import { InlineText } from "@/components/guides/GuideBlocks";
import { guidePath, guides } from "@/lib/guides";
import { countryByCode } from "@/lib/countries";

/**
 * /guides — the index.
 *
 * Cards come from src/data/guides.json in file order, which is also the order
 * scripts/prerender.mjs writes them in, so the static HTML and this page list
 * the same articles in the same order.
 */
const Guides = () => {
  const articles = guides();

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Keep in step with the /guides entry generated by guideRoutes() in
          scripts/guides.mjs — that copy is what crawlers read, this one only
          applies after hydration. */}
      <SEO
        title="Fishing Guides — AnglerDeck"
        description="In-depth guides to the rules that decide where you can fish — licences, permits and access, compared across countries and sourced to official fisheries agencies."
        canonicalPath="/guides"
      />
      <Header />

      <main
        id="main-content"
        className="flex-1 container mx-auto px-4 lg:px-8 py-12 pt-28"
      >
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-3xl"
        >
          <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
            Fishing Guides
          </h1>
          <p className="text-lg text-muted-foreground">
            Long-form guides to the rules that decide where you can actually fish
            — licences, permits, access and the exceptions that catch visiting
            anglers out. Each one compares countries side by side and links every
            claim to the agency that made the rule.
          </p>
        </motion.div>

        <div className="grid gap-6 mt-10 lg:grid-cols-2">
          {articles.map((article, index) => {
            const countryNames = article.countries
              .map((code) => countryByCode(code)?.name)
              .filter(Boolean);

            return (
              <motion.article
                key={article.slug}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: Math.min(index * 0.05, 0.4) }}
              >
                <Link
                  to={guidePath(article.slug)}
                  className="group flex h-full flex-col p-6 rounded-2xl border border-border/50 bg-card hover:border-accent/50 transition-colors"
                >
                  <div className="flex items-start gap-3">
                    <div className="p-2 rounded-lg bg-accent/10 shrink-0">
                      <BookOpen className="w-5 h-5 text-accent" />
                    </div>
                    <h2 className="text-xl font-semibold text-foreground group-hover:text-accent transition-colors">
                      {article.headline}
                    </h2>
                  </div>

                  <p className="mt-4 text-muted-foreground leading-relaxed">
                    <InlineText text={article.summary} />
                  </p>

                  {countryNames.length > 0 && (
                    <p className="mt-4 text-xs text-muted-foreground">
                      Covers {countryNames.join(", ")}
                    </p>
                  )}

                  <div className="mt-auto pt-5 flex items-center justify-between text-sm">
                    <time
                      dateTime={article.datePublished}
                      className="text-muted-foreground"
                    >
                      {article.datePublished}
                    </time>
                    <span className="flex items-center gap-1 text-accent">
                      Read guide
                      <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
                    </span>
                  </div>
                </Link>
              </motion.article>
            );
          })}
        </div>

        <div className="flex flex-wrap gap-4 mt-12 text-sm">
          <Link to="/regulations" className="text-accent hover:underline">
            Regulations and licences by country
          </Link>
          <Link to="/spots" className="text-accent hover:underline">
            Browse all fishing spots
          </Link>
          <Link to="/map" className="text-accent hover:underline">
            View the fishing map
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Guides;
