-- Access-model records for the five lodge- and outfitter-only waters (2026-07-29)
--
-- These spots have no public road access and no walk-on option. The honest and
-- useful record is the access model itself plus the permit machinery that
-- creates it — each sourced here to the relevant provincial, regional or
-- federal fisheries authority rather than to a lodge selling the trip:
--
--   Río Grande     — TdF Ministerio de Producción y Ambiente (SIPED / SAPTDF)
--   Jurassic Lake  — Santa Cruz SIPESQ, Secretaría de Pesca y Acuicultura
--   Kola           — Rosrybolovstvo register of designated fishing plots
--   Kamchatka      — Glavrybvod North-East branch, Far East basin rules
--   Rio Negro      — MPF/TRF1 on Funai visitation plans; SEMA/IPAAM licensing

UPDATE public.spots SET access = '{"shore": true, "boat": false, "notes": "NOT OPEN BANK FISHING: the Río Grande sea trout beats are allocated and reserved, not walked onto. Access runs through the provincial permit system and, in practice, through the lodges holding the productive water — book a season ahead. PERMITS: bought digitally through the Sistema de Administración de Permisos de Pesca (SAPTDF), with angler registration and authorisation handled by the Sistema de Información de Pesca Deportiva (SIPED). Permits are also sold by designated vendors in Río Grande, Ushuaia and Tolhuin. SAPTDF is also where access to authorised sectors is reserved, and some are capped — Río Claro, for instance, is limited to ten rods a day. If you reserve and do not turn up you must justify it within 24 hours or be suspended from the system. IMPORTANT: a Tierra del Fuego permit is valid only in Tierra del Fuego and is not part of the Patagonian permit scheme, so a mainland Patagonian permit will not cover you here. SEASON: set by resolution of the Secretaría de Ambiente each year — the 2025/2026 season ran 1 November to 1 May. RELEASE: on the Río Grande and its tributaries, the Candelaria, Ona, Menéndez, Rasmussen, Moneta and Herminita, return of all salmonids is mandatory. A limited kill is allowed on unrestricted provincial waters early in the season, but from 1 March return of all catches becomes mandatory province-wide except where special conditions apply. Daytime fishing only, fly or spinning. Permits are free for children under 12, retirees and people with disabilities. Check the current resolution before booking.", "sourceUrl": "https://prodyambiente.tierradelfuego.gob.ar/pesca-deportiva-tdf/"}'::jsonb, updated_at = now() WHERE slug = 'rio-grande-sea-trout';

UPDATE public.spots SET access = '{"shore": true, "boat": false, "notes": "NO PUBLIC ROAD ACCESS: Strobel is a remote plateau lake reached across private estancia land, and it is fished through the lodges that hold that access, booked well in advance. There is no walk-on option, and the practical planning question is which lodge rather than which bank. PERMIT: a Santa Cruz sport fishing permit is personal, obligatory and non-transferable, obtained through SIPESQ at pesca.santacruz.gob.ar and carried printed or digital, to be shown with photo ID whenever a control officer asks. Permits come as daily, weekly or seasonal, and non-resident rates are several times the resident ones; over-65s, retirees, pensioners, under-12s, people with disabilities and Falklands veterans fish free. The provincial season ran 1 October to 1 May in 2025/2026. CATCH AND RELEASE: Strobel and the Barrancoso are mandatory-release water. Single barbless hooks are required during catch-and-release periods and lead weights are prohibited. DIDYMO — PLAN FOR THIS BEFORE YOU TRAVEL: Santa Cruz runs a control plan for the invasive alga Didymosphenia geminata. Strobel and the Barrancoso require daily mandatory disinfection certification, anglers entering the province are required to use new waders and boots, and service providers must issue sanitised gear to their clients. Turning up with used kit from another river is not acceptable. Enforcement is shared between the provincial police, Prefectura Naval Argentina and Gendarmería Nacional. Check the current Santa Cruz annex before booking.", "sourceUrl": "https://pesca.santacruz.gob.ar/ayuda/permisos"}'::jsonb, updated_at = now() WHERE slug = 'jurassic-lake-strobel';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "THE ACCESS MODEL: Atlantic salmon rivers in Murmansk Oblast are not open water. They are divided into designated fishing plots (рыболовные участки) allocated by auction to a small number of licensed organiser companies, and those organisers issue the permit (путёвка) and sell the fishing as an organised trip. There is no walk-on salmon fishing on the named beats. This is why Kola trips are booked far ahead and priced as packages rather than day tickets. WHICH WATER: the plots include named sections on the Kola river itself — Kola 1 near Molochny, Kola 2 near Shonguy, and Kola 3 — plus a section on the Kitza, a Kola tributary, and rivers including the Ura, Titovka and Pechenga. The Ministry of Natural Resources, Ecology and Fisheries of Murmansk Oblast publishes the list of plots allocated for organised amateur fishing, and the Federal Agency for Fishery publishes the national register of fishing plots for every Russian region together with a map showing what may be caught where. The Barents-Beloe Sea territorial directorate of the Federal Agency for Fishery runs the auctions that determine who organises fishing on each plot. The Rules of Fishing for the Northern fishery basin apply on top of the plot operator''s conditions. Confirm the plot, the organiser and the current rules before committing to a trip.", "sourceUrl": "https://fish.gov.ru/otraslevaya-deyatelnost/organizacziya-rybolovstva/perechni-rybolovnyh-uchastkov-subektov-rossijskoj-federaczii/"}'::jsonb, updated_at = now() WHERE slug = 'kola-peninsula-salmon';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "THE ACCESS MODEL: recreational fishing on public waters in Russia is in general free and needs no permit, but Pacific salmon are an exception — the Far East basin fishing rules list them as species that may be taken only under a permit (путёвка) on a designated fishing plot. That single rule is what turns Kamchatka salmon fishing into an operator-led activity: the productive rivers are remote, the plots are held by licensed organisers, and the fishing is bought as a package booked well in advance rather than as a day ticket. HOW THE PERMIT WORKS: it is paid for and issued by the plot operator, delivered as a PDF to print and carry alongside your passport or other identity document. When you finish fishing you must write the volume of your catch onto the permit, confirmed by the operator, and report it the same day by message or photo, giving your name, the date, the permit number and the quantity taken. The North-Eastern branch of Glavrybvod organises amateur and sport fishing on the plots and publishes a named instructor and phone number for each; its recreational fishing section can be reached on 8 (4152) 23-58-89. Some Kamchatka salmonids are protected and some areas sit inside nature reserves or border zones with their own entry requirements, so confirm the status of the specific river and species with the operator and the regional authority before booking. Check current rules.", "sourceUrl": "https://sv.glavrybvod.ru/novosti/uvazhaemye-rybolovy-lyubiteli-vstupili-v-silu-novye-pravila-rybolovstva-dlya-dalnevostochnogo-rybohozyajstvennogo-bassejna/"}'::jsonb, updated_at = now() WHERE slug = 'kamchatka-rainbow-trout';

UPDATE public.spots SET access = '{"shore": false, "boat": true, "notes": "THE ACCESS MODEL: this is live-aboard and lodge fishing on a remote river, run from mother-ships and their tenders rather than from the bank, and booked a season ahead. INDIGENOUS LAND — CHECK THIS BEFORE YOU BOOK: much of the Rio Negro basin is demarcated Indigenous Land, and sport fishing on it requires a visitation plan approved in advance and in writing by Funai, the national indigenous peoples foundation, together with the consent of every Indigenous community involved. Consent has to be unanimous — a single community refusing, as the Areal community did, voids the authorisation. This is enforced, not theoretical: the Federal Regional Court upheld an immediate prohibition on one operator fishing the Jurubaxi-Téa Indigenous Land and Indigenous lands across the Rio Negro basin, with a daily fine of R$100,000 for breach, removal of the company''s personnel and equipment, and powers for federal agencies to inspect and seize. Ask any operator to show you the Funai-approved visitation plan and the community consents covering the water it intends to fish. LICENCES: amateur sport fishing in Barcelos and Santa Isabel do Rio Negro needs a special licence issued by those municipalities for the fishing period, in addition to the national amateur fishing licence. The agencies, hotels, boats and tournaments themselves must be licensed by IPAAM, the Amazonas environmental protection institute. FISHING AGREEMENTS: the Amazonas environment department SEMA, with Sepror, has approved acordos de pesca covering the Rio Negro and the Quiuini, Aracá, Demeni, Padauiri and Caurés rivers, which zone stretches of water between commercial, sport, management, preservation and subsistence fishing. Which stretch you may fish depends on that zoning. Check current rules before booking.", "sourceUrl": "https://www.mpf.mp.br/o-mpf/unidades/prr1/noticias/mpf-obtem-no-trf1-a-manutencao-das-restricoes-a-pesca-esportiva-irregular-em-terras-indigenas-no-amazonas"}'::jsonb, updated_at = now() WHERE slug = 'rio-negro-peacock-bass';
