-- Verified access details — batch 14
--
-- 10 spot(s). Every sourceUrl is an official government, park-authority or fisheries-body page (CLAUDE.md content rules 1-3).
-- Apply by hand in the SQL Editor, then rebuild (migration first, then build).
--
-- saltstraumen-coalfish: Miljodirektoratet Naturbase plan register (fpnv.naturbase.no, VV00003081) read twice via WebFetch with verbatim quotes: management plan approved 10.02.2025, revision planned 2035; "Det er et intensivt sportsfiske, spesielt i selve Saltstraumen"; divers cleared 705 kg of lost lures in 2024 (about 23,500 lures at an assumed 30 g); the manager will arrange annual diver clean-ups. Lovdata protection regulation (FOR-2013-06-21-694) par.4 exempts fishing under the salmon and inland fish act and marine-resource harvesting (not kelp/seaweed). No parking or ramp detail included: the only parking source found was a non-official hiking site. Earlier skip note superseded.
--
-- gaula-river-salmon: Miljodirektoratet page "Betale fiskeravgift for laksefiske", read via WebFetch (Norwegian): anyone over 18 fishing salmon, sea trout or sea char in a watercourse must pay the state fiskeravgift; under-18s are exempt from the fee; fiskeravgift is separate from the local fiskekort, which is bought from the landowner or river administrator. Advisory-style record: the river-specific rules for the Gaula (season dates, catch reporting, release rules) are published by river-owner associations, not an official page, so none are restated. Statsforvalteren i Trondelag pages that would cover them returned 404 via WebFetch. Fine amount deliberately omitted.
--
-- namsen-river-salmon: Miljodirektoratet page "Betale fiskeravgift for laksefiske", read via WebFetch (Norwegian): anyone over 18 fishing salmon, sea trout or sea char in a watercourse must pay the state fiskeravgift; under-18s are exempt from the fee; fiskeravgift is separate from the local fiskekort, which is bought from the landowner or river administrator. Advisory-style record: the river-specific rules for the Namsen (season dates, catch reporting, release rules) are published by river-owner associations, not an official page, so none are restated. Statsforvalteren i Trondelag pages that would cover them returned 404 via WebFetch. Fine amount deliberately omitted.
--
-- femunden-grayling: Statskog page "Femundsmarka" (state land manager) read via WebFetch (Norwegian), plus Engerdal Fjellstyre page "Hvordan kjope fiskekort" (statutory mountain board): a shared Femundsmarka card covers all waters inside the national park in Engerdal and Roros and is sold online (inatur.no) and by SMS; species listed are char, whitefish, perch, pike, burbot, and trout and grayling in the rivers; Statskog states fishing is free under 20 and over 67; entry points named are Feragen, Feragsdammen, Langen and the Faemund 2 shuttle boat from Synnervika to Roa; Statskog rents cabins at Synnervika, Feragsdambua, Hestbetaasbua and Nordviksanden. Engerdal Fjellstyre says permits are now sold digitally only and that the park card is valid only inside the park boundary; outside it the ordinary Engerdal permit applies. No parking detail stated on either page, so none given. No prices stated.
--
-- senja-halibut: Fiskeridirektoratet (Directorate of Fisheries) page "Freda og delvis freda artar" under Fritidsfiske, read via WebFetch with verbatim quotes: halibut fishing is forbidden year-round south of Stad (62N), and north of Stad from 20 December to 20 April, for all gear. Senja (about 69N) is north of Stad. The page carries no update date and a 2026 halibut regulation consultation exists on the same site, so the record states the closed period with a check-current-rules pointer. Bag/gear/hook numbers and the tourist export allowance were seen in search summaries and deliberately left out (rule 3). No access or ramp page found; this is a regulation-only record.
--
-- nagara-river-ayu: Gifu Prefecture official page "Gifu-ken no gyogyoken" (pref.gifu.lg.jp/page/11131.html), read via WebFetch (Japanese): on Type 5 common fishing-right waters, recreational anglers need the permission of the fishing cooperative that holds the right, and each area has its own recreational fishing rules (yuryo kisoku); the Nagara River is split among several cooperatives (Kiso-Nagara Lower River, Nagara River, Nagara River Central, Gujo, Tsubo River, Miyama, Itatori Upper River); the page states the current rights run 1 Jan 2026 to 31 Dec 2035. The page does not name the permit or give fees or seasons, so none are stated (fees and seasons appeared only on a cooperative site and search summaries). Previous skip note superseded.
--
-- rio-sao-francisco: IEF-MG (Instituto Estadual de Florestas, Minas Gerais state forestry institute) page "Piracema", read via WebFetch with verbatim quotes (Portuguese): the piracema/defeso runs from 1 November to 28 February of the following year; fishing is prohibited, amateur fishing is allowed only for non-native (exotic/alochthonous) species and hybrids, native fish caught accidentally must be released, and anglers must hold a current amateur fishing licence (types A1 shore, A2 boat, A3 underwater); the page points to Portaria IEF 154/2011 for the Sao Francisco basin. Applies to the Minas Gerais side only: the Bahia side is under Bahia rules, not read, so the record says so. Ibama and MMA pages on the same topic returned "Conteudo Restrito" via WebFetch. Existing regulations said the closure was "roughly" Nov-Feb; this gives the stated dates.
--
-- campeche-tarpon: CONAPESCA (Mexican federal fisheries commission) procedure page CONAPESCA-01-016 "Permiso para Pesca Deportivo-Recreativa", read via WebFetch with verbatim quotes (Spanish): the permit is available to Mexican and foreign individuals; fishing from land "no requerira de permiso"; fishing aboard a vessel requires the permits under the Ley Federal de Derechos; permit types are daily, weekly, monthly, annual and excursion, obtained at CONAPESCA offices or online (e5cinco). National rule, not specific to Campeche; no spot-specific official page found, so the record is deliberately limited to the permit rule and carries no ramp, parking or facility claims. Fees omitted.
--
-- lake-el-salto-bass: CONAPESCA (Mexican federal fisheries commission) procedure page CONAPESCA-01-016 "Permiso para Pesca Deportivo-Recreativa", read via WebFetch with verbatim quotes (Spanish): the permit is available to Mexican and foreign individuals; fishing from land "no requerira de permiso"; fishing aboard a vessel requires the permits under the Ley Federal de Derechos; permit types are daily, weekly, monthly, annual and excursion, obtained at CONAPESCA offices or online (e5cinco). National rule, not specific to Lake El Salto; no spot-specific official page found, so the record is deliberately limited to the permit rule and carries no ramp, parking or facility claims. Fees omitted.
--
-- lake-baccarac-bass: CONAPESCA (Mexican federal fisheries commission) procedure page CONAPESCA-01-016 "Permiso para Pesca Deportivo-Recreativa", read via WebFetch with verbatim quotes (Spanish): the permit is available to Mexican and foreign individuals; fishing from land "no requerira de permiso"; fishing aboard a vessel requires the permits under the Ley Federal de Derechos; permit types are daily, weekly, monthly, annual and excursion, obtained at CONAPESCA offices or online (e5cinco). National rule, not specific to Lake Baccarac; no spot-specific official page found, so the record is deliberately limited to the permit rule and carries no ramp, parking or facility claims. Fees omitted.
--
-- Also verified this pass, no per-spot record written (see CLAUDE.md section 6, Poland):
-- - szczecin-lagoon: Polish statewide rule VERIFIED on official Wody Polskie pages (gov.pl/web/wody-polskie-szczecin/zasady-sprzedazy-zezwolen-nasze-lowiska and gov.pl/web/wody-polskie-poznan/zasady-sprzedazy-zezwolen): "Cudzoziemcy przebywajacy czasowo w Polsce sa zwolnieni z obowiazku posiadania karty wedkarskiej. Zezwolenie jest wymagane."; permits sold only electronically via Wirtualny Informator Rzeczny (wir.wody.gov.pl). Neither page names Szczecin Lagoon or any specific water, and the lagoon may fall under sea-fisheries rules, so no per-spot record was written; a statewide note on every Polish spot would be thin padding. Resolves the open Poland item in CLAUDE.md section 6 for the exemption itself.
--

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"Saltstraumen is a marine protected area. Its protection regulation allows fishing under Norwegian fishing law and general boat traffic, but bans harvesting kelp and seaweed. The approved management plan (10 February 2025) records intensive sport fishing, especially in the strait itself, and lost lures littering the seabed: divers removed 705 kg of lost lures in 2024, and the plan provides for annual diver clean-ups. Avoid snag-prone ground, take lost line and tackle seriously, and follow any signs. Check current Norwegian fishing and protected-area rules before fishing.","sourceUrl":"https://fpnv.naturbase.no/Plan/View?naturvernId=VV00003081"}'::jsonb, updated_at = now() WHERE slug = 'saltstraumen-coalfish';

UPDATE public.spots SET access = '{"notes":"Norway requires two separate things to fish salmon, sea trout or sea char in a river such as the Gaula: the state fishing fee (fiskeravgift), payable by anyone over 18, and a local fishing permit (fiskekort) bought from the landowner or river administrator. Under-18s do not pay the fee. Season dates, catch reporting and release rules are set locally and change by year, so read the current rules for the river before you go and confirm them with the local permit seller.","sourceUrl":"https://www.miljodirektoratet.no/ansvarsomrader/arter-naturtyper/fiske/nar-kan-jeg-fiske-laks-sjoorret-og-sjoroye/betale-fiskeravgift/"}'::jsonb, updated_at = now() WHERE slug = 'gaula-river-salmon';

UPDATE public.spots SET access = '{"notes":"Norway requires two separate things to fish salmon, sea trout or sea char in a river such as the Namsen: the state fishing fee (fiskeravgift), payable by anyone over 18, and a local fishing permit (fiskekort) bought from the landowner or river administrator. Under-18s do not pay the fee. Season dates, catch reporting and release rules are set locally and change by year, so read the current rules for the river before you go and confirm them with the local permit seller.","sourceUrl":"https://www.miljodirektoratet.no/ansvarsomrader/arter-naturtyper/fiske/nar-kan-jeg-fiske-laks-sjoorret-og-sjoroye/betale-fiskeravgift/"}'::jsonb, updated_at = now() WHERE slug = 'namsen-river-salmon';

UPDATE public.spots SET access = '{"facilities":["cabin rental"],"notes":"Statskog and Engerdal Fjellstyre sell a shared Femundsmarka fishing card that covers all waters inside Femundsmarka National Park in Engerdal and Roros. It is sold online through inatur.no and by SMS, and it is valid only inside the park boundary; elsewhere around Femund the ordinary Engerdal permit applies. Statskog names Feragen, Feragsdammen and Langen as starting points, and a shuttle boat, Faemund 2, runs from Synnervika to Roa. Statskog rents cabins at Synnervika, Feragsdambua, Hestbetaasbua and Nordviksanden. Statskog lists char, whitefish, perch, pike and burbot in the lakes and trout and grayling in the rivers, and says fishing is free for those under 20 and over 67. Check the current card rules before you go.","sourceUrl":"https://www.statskog.no/vare-perler/turperler/femundsmarka"}'::jsonb, updated_at = now() WHERE slug = 'femunden-grayling';

UPDATE public.spots SET access = '{"notes":"Fiskeridirektoratet, the Norwegian Directorate of Fisheries, lists halibut as a protected species for recreational fishers: fishing for it is forbidden all year south of Stad (62 degrees north), and north of Stad, which includes Senja, it is forbidden from 20 December to 20 April, for all gear. Halibut rules are reviewed often, so check the Directorate of Fisheries for the current regulations, including any gear limits, before you fish.","sourceUrl":"https://www.fiskeridir.no/Fritidsfiske/Artar/freda-og-delvis-freda-artar"}'::jsonb, updated_at = now() WHERE slug = 'senja-halibut';

UPDATE public.spots SET access = '{"notes":"Gifu Prefecture explains that fishing on the Nagara River is governed by fishing rights held by several local fishing cooperatives, each covering a section of the river (for example the Nagara River Central, Gujo, Tsubo River and Itatori Upper River cooperatives, and the Kiso-Nagara Lower River cooperative downstream). Anglers need the permission of the cooperative for the stretch they fish and must follow that cooperative''s own recreational fishing rules. Find out which cooperative covers your stretch, and read its current rules, seasons and permit requirements, before you fish.","sourceUrl":"https://www.pref.gifu.lg.jp/page/11131.html"}'::jsonb, updated_at = now() WHERE slug = 'nagara-river-ayu';

UPDATE public.spots SET access = '{"notes":"The Minas Gerais state forestry institute (IEF-MG) says the piracema closed season on its rivers, including the Sao Francisco basin, runs from 1 November to 28 February. In that period fishing is prohibited except amateur fishing for non-native species and hybrids, and native fish caught by accident must be released. A current amateur fishing licence is required to carry fishing gear and catch. This describes the Minas Gerais side only; the Bahia bank is governed by Bahia rules. Check the current state and federal rules for the stretch you fish.","sourceUrl":"https://www.ief.mg.gov.br/piracema"}'::jsonb, updated_at = now() WHERE slug = 'rio-sao-francisco';

UPDATE public.spots SET access = '{"notes":"CONAPESCA, the Mexican federal fisheries commission, says recreational fishing from shore needs no federal permit, but fishing from a boat requires a recreational fishing permit, which foreign visitors can obtain. Permits come as daily, weekly, monthly, annual and excursion types and are issued at CONAPESCA offices or through its online system. Check the current CONAPESCA requirements and any local protected-area rules before you fish.","sourceUrl":"https://www.gob.mx/conapesca/documentos/conapesca-01-016-pesca-deportivo-recreativa"}'::jsonb, updated_at = now() WHERE slug = 'campeche-tarpon';

UPDATE public.spots SET access = '{"notes":"CONAPESCA, the Mexican federal fisheries commission, says recreational fishing from shore needs no federal permit, but fishing from a boat requires a recreational fishing permit, which foreign visitors can obtain. Permits come as daily, weekly, monthly, annual and excursion types and are issued at CONAPESCA offices or through its online system. Check the current CONAPESCA requirements and any local protected-area rules before you fish.","sourceUrl":"https://www.gob.mx/conapesca/documentos/conapesca-01-016-pesca-deportivo-recreativa"}'::jsonb, updated_at = now() WHERE slug = 'lake-el-salto-bass';

UPDATE public.spots SET access = '{"notes":"CONAPESCA, the Mexican federal fisheries commission, says recreational fishing from shore needs no federal permit, but fishing from a boat requires a recreational fishing permit, which foreign visitors can obtain. Permits come as daily, weekly, monthly, annual and excursion types and are issued at CONAPESCA offices or through its online system. Check the current CONAPESCA requirements and any local protected-area rules before you fish.","sourceUrl":"https://www.gob.mx/conapesca/documentos/conapesca-01-016-pesca-deportivo-recreativa"}'::jsonb, updated_at = now() WHERE slug = 'lake-baccarac-bass';

