-- Verified access details — batch 10
--
-- 16 spot(s) with records, 12 skipped. Every sourceUrl is an official
-- government, park-authority, council or fisheries-body page (CLAUDE.md content rules 1-3).
-- Apply by hand in the SQL Editor, then rebuild (migration first, then build).
--
-- exmouth-ningaloo-flats: DBCA (WA Parks and Wildlife Service) Explore Parks pages, loaded in a real browser: the Bundegi Beach page states the beach is in a Recreation Zone where shore fishing is permitted, with toilets and a boat launching area; the Tantabiddi Boat Ramp page lists toilets and a boat ramp, says fishing is permitted in the adjacent recreation zone and not in Tantabiddi Sanctuary Zone. Existing regulations already flag the sanctuary zones and boat-licence point; unchanged.
--
-- coorong-mulloway-surf: SA National Parks and Wildlife Service (parks.sa.gov.au), Coorong National Park beach-camping page, loaded in a real browser: ocean beach is 4WD-only, permit per vehicle, annual closure north of Tea Tree Crossing 24 Oct-24 Dec, no facilities on the beach. No ramp/parking detail for the surf beach itself, left out.
--
-- lake-jindabyne-trout: Snowy Hydro (the lake operator, government-owned) visitor-guidelines page: foreshore access is through designated points with basic toilet and picnic facilities; boating safety is enforced by Maritime NSW, fisheries rules by Fisheries NSW. Snowy Monaro Regional Council foreshore pages and NSW DPIRD returned no access detail (DPI has moved to dpird.nsw.gov.au). Kept deliberately short: no ramp locations stated as fact beyond what the source says.
--
-- albany-king-george-sound: WA Department of Transport (transport.wa.gov.au) Albany Emu Point Boat Harbour page, loaded in a real browser: three-lane ramp with two floating access jetties, public car and trailer parking, toilets/showers and fish-cleaning bench maintained by the City of Albany. Emu Point is in Oyster Harbour, which opens to King George Sound; stated as such. No official shore-access page found for Albany foreshore itself.
--
-- lake-st-clair-smallmouth: Huron-Clinton Metroparks (a regional public park authority) Lake St. Clair Metropark page, loaded in a real browser: address, hours, vehicle/boat pass requirement, fishing, boating and a marina on Lake St. Clair, ice fishing in winter. MDHHS Eat Safe Fish main page confirms the state publishes annual area fish-consumption guides (2026 edition released 8 June 2026); the Lake St. Clair-specific advisory text could not be read (MDHHS PDF blocked in the browser viewer), so only the pointer is stated, no advisory detail. Consumption detail is left to MDHHS.
--
-- laguna-madre-redfish: US National Park Service Padre Island National Seashore, Bird Island Basin Boat Ramp page: the park's only developed ramp, on the Laguna Madre; paved ramp and dock, gravel paddle launch, small pier with fish-cleaning tables, trailer parking, accessible vault toilets, ramp pass required. Fees deliberately not restated (they change).
--
-- drawa-river-trout: Drawienski Park Narodowy (the national park authority) "Wedkarstwo" page, read via WebFetch: Drawa angling allowed from Lake Dubie Poludniowe (Adamowo) to the bridge at the Kamienna power station, 1 Jan-15 Mar and 1 Jul-31 Dec; lakes Sitno and Ostrowieckie 1 Apr-30 Nov; daily limits on the number of anglers per water; the only document entitling amateur fishing in park waters is the park ticket ("licence") together with an angler's card and a catch register; Drawa is spinning and fly only (fly on barbless hooks); no angling from floating equipment, no ice fishing, no live or dead fish as bait on the Drawa, no groundbait; tickets from park tourist information points or bilety.dpn.pl. CONTRADICTION FIXED: the existing regulations said "Visitors are exempt from the karta wedkarska but need a water permit". That exemption is UNVERIFIED (CLAUDE.md item 6), and for park waters the park states it requires the angler's card; the line was replaced. A separate Wody Polskie RZGW Szczecin permit page does say foreigners temporarily in Poland are exempt from the fishing-card obligation for the waters that permit covers; this may be how the national exemption should eventually be sourced, but it is not stated for park waters so it is not used here.
--
-- baltic-coast-sea-trout: Polish Main Inspectorate of Sea Fisheries (GIRM) recreational-fishing page on gov.pl, read via WebFetch: recreational fishing in Polish sea waters is done on the basis of proof of payment (weekly, monthly or annual); validity runs from the day of payment; carry an identity document and proof of payment; certain catches need reporting. Fees deliberately not restated. Existing regulations (sea permit, weekly or annual) consistent and unchanged; the page does not discuss sea-trout closures, so none added.
--
-- mataura-river: Fish & Game New Zealand (statutory sports-fish manager) Mataura River page, loaded in a real browser: upper reaches run a voluntary beat system, good access along the river with an access map on the same site, open year-round below Mataura Island Bridge, season extended below Gore. CONTRADICTION FIXED: the existing regulations said "Season generally runs Oct-Apr — most water is closed in winter", which is wrong for the lower river; replaced with section-by-section wording and a pointer to Fish & Game Southland for current dates.
--
-- lake-wanaka-trout: Queenstown Lakes District Council (the local authority) boat-ramp permit page for Lakes Wanaka and Hawea: a permit is required per trailer, bought at QLDC offices in Queenstown or Wanaka, displayed on the trailer; fees not restated. Fish & Game licence line in the existing regulations unchanged. No per-ramp detail on that page, so no ramp location is stated.
--
-- marlborough-sounds-blue-cod: MPI (NZ Ministry for Primary Industries) Marlborough Sounds blue cod page, loaded in a real browser: no blue cod may be taken between 1 September and 10 January inclusive (closed season extended from 19 December). CONTRADICTION FIXED: existing regulations said only that blue cod has seasonal rules; the closed season is now stated. Bag and size numbers deliberately not included. No ramp-level official source found, so this is a notes-only record.
--
-- motueka-river: Fish & Game New Zealand, Nelson/Marlborough region Motueka Catchment page, loaded in a real browser: under an hour from Nelson, abundant easy access to the main river and tributaries, Water Conservation Order, a published Motueka River Access Guide (PDF, updated Feb 2024). No specific access point/parking detail readable, so none stated. Existing regulations not contradicted by this page.
--
-- kaikoura-offshore: Kaikoura District Council (local authority) Airport, Harbour & Wharfs page, loaded in a real browser: South Bay Marina on the southern side of the Kaikoura Peninsula has a seawall, slipway, fuel facility, public toilet, boat wash-down area and parking for cars, trailers and boats; a recreational slipway fee applies (amounts not restated); ECAN Harbourmaster contact. Existing regulations (no licence, marine mammal sanctuary, limits) not contradicted.
--
-- rotorua-lakes-trout: Fish & Game New Zealand, Eastern region page, loaded in a real browser: published angler-access brochures for the Rotorua lakes, and the biosecurity access conditions that matter most to boaties (Lake Okataina automated-gate process under an MPI Controlled Area Notice; wash-station requirement for boats that have been in the Waikato River in the previous 30 days). Existing regulations not contradicted.
--
-- river-wye-barbel: Environment Agency (navigation authority for the Wye from Hay to Bigsweir Bridge) gov.uk page "Information to help boaters on the River Wye": no absolute right of access to the bank downstream of Hay Bridge, landowner permission needed to launch or land, none for camping or picnicking without it. This is an access caveat for boat-based anglers; no bank-access or parking detail found on an official page. Existing regulations (day tickets from the controlling club or landowner) are consistent and unchanged.
--
-- norfolk-broads-pike: Broads Authority (the national-park authority) Angling page, loaded in a real browser, cross-checked against the Environment Agency Anglian-region byelaws page on gov.uk: licence requirement, publicly accessible fishing platforms, angling allowed from most Broads Authority 24-hour moorings unless signed otherwise, mooring etiquette, angling-club stretches need permission, and the coarse close season of 15 March to 15 June. CONTRADICTION FIXED: the existing regulations said the coarse close season "applies on the rivers but not on most still broads"; both official pages say it applies on the Broads waterways generally, with exemptions only for some private stillwaters/fisheries, so the line was rewritten. Pike welfare rules line kept.
--
-- Not included this batch:
-- - lake-of-the-woods-walleye: MN DNR page found only statewide access rules (24h, trailer + carry-in, no launch fee outside parks) and a pointer to mercury guidelines; no lake-specific access page readable (county access map is a PDF). Too generic to count as verified detail.
-- - lake-winnipeg-walleye: Manitoba provincial-park pages found (Birch Point etc.) are not the Gimli/Matlock shoreline; no official page for the specific Lake Winnipeg access at Gimli found in the time-box.
-- - gaspe-salmon-quebec: Sepaq/ZEC pages cover specific rivers/reserves (Matane, Port-Daniel, Saint-Anne); none confirmed for the Gaspe river sectors this spot describes.
-- - skeena-river-steelhead: BC government classified-waters page returned only an introduction; the synopsis is a PDF unreadable in this environment. Not enough readable official detail.
-- - raba-river-trout: NOT RESEARCHED in this pass.
-- - san-river-grayling: NOT RESEARCHED in this pass.
-- - solina-lake: NOT RESEARCHED in this pass.
-- - oder-river-asp: NOT RESEARCHED in this pass.
-- - dunajec-river-trout: Pieninski National Park pages found concern rafting; no official fishing-access page located (search explicitly found none).
-- - szczecin-lagoon: Wody Polskie RZGW Szczecin permit page found and read: permits are sold online only, a fishing card is required but foreigners temporarily staying in Poland are exempt from it; the page does not name Zalew Szczecinski and lists no zones or seasons. Not written as an access record because it would be a statewide permit note; the exemption wording is reported in the cover note as a possible source for the unverified Poland claim.
-- - river-towy-wales: NRW and gov.uk pages found cover the rod licence and SAC status only; no official page with Towy access points, parking or ramps found. Existing licence line confirmed correct (licence is issued by the Environment Agency and valid in Wales and England) but confirming a regulation is not an access record.
-- - cornwall-bass-marks: Only general CIFCA and Cornwall Council car-park pages found; no official page on the specific rock marks or shore access. Guide-site consensus is not a source.
--

UPDATE public.spots SET access = '{"shore":true,"boat":true,"ramp":"Two DBCA-listed boat launches: Bundegi (north of Exmouth, for Exmouth Gulf and the northern marine park) and Tantabiddi Boat Ramp (for the northern part of Ningaloo Marine Park)","facilities":["Toilets (Bundegi and Tantabiddi)"],"notes":"Shore fishing is permitted on Bundegi Beach, which lies in a Recreation Zone of Ningaloo Marine Park. Fishing is not permitted in sanctuary zones such as Tantabiddi and Bundegi Sanctuary Zones. Check the zone map before fishing and confirm current WA DPIRD licence and marine park rules.","sourceUrl":"https://exploreparks.dbca.wa.gov.au/site/bundegi-beach"}'::jsonb, updated_at = now() WHERE slug = 'exmouth-ningaloo-flats';

UPDATE public.spots SET access = '{"shore":true,"notes":"The Coorong ocean beach is 4WD-access only and experience in soft sand driving is essential; a permit is required for each vehicle and there are no facilities on the beach. The beach north of Tea Tree Crossing is closed to vehicles from 24 October to 24 December each year to protect nesting hooded plovers. Ocean beach conditions change with erosion and dune collapses, and NPWS does not recommend driving at night or towing trailers there. Call NPWS on (08) 7133 7270 for current conditions.","sourceUrl":"https://www.parks.sa.gov.au/parks/coorong-national-park/booking/71721"}'::jsonb, updated_at = now() WHERE slug = 'coorong-mulloway-surf';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"facilities":["Basic toilets and picnic tables at designated access points"],"notes":"Snowy Hydro asks visitors to access the lake foreshore only through its designated access points, which generally have basic toilet and picnic facilities. Boating safety on the alpine lakes is enforced by Maritime NSW and fishing rules by Fisheries NSW. Check current NSW freshwater fishing rules before fishing.","sourceUrl":"https://www.snowyhydro.com.au/visit/guidelines-for-visiting-the-scheme/"}'::jsonb, updated_at = now() WHERE slug = 'lake-jindabyne-trout';

UPDATE public.spots SET access = '{"boat":true,"ramp":"Emu Point Boat Harbour (Oyster Harbour, 9 km from central Albany): three-lane boat ramp with two floating universal-access jetties","parking":"Public car and boat-trailer parking near the harbour entrance","facilities":["Public toilets and showers","Fish cleaning bench with taps"],"notes":"Emu Point is in the sheltered waters of Oyster Harbour, which connects to King George Sound. Check tide and wave conditions through WA Department of Transport before heading out, and confirm current WA DPIRD licence and marine park rules.","sourceUrl":"https://www.transport.wa.gov.au/marine/boating-facilities/locations/albany-emu-point-harbour"}'::jsonb, updated_at = now() WHERE slug = 'albany-king-george-sound';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"ramp":"Lake St. Clair Metropark, 31300 Metro Parkway, Harrison Township, MI, has a marina on Lake St. Clair","parking":"Park entry requires a daily vehicle or boat pass or an annual pass, sold by the Metroparks","notes":"Lake St. Clair Metropark lists fishing and boating among its activities and is open 6 a.m. to 10 p.m. on weekdays and 6 a.m. to 11 p.m. at weekends; ice fishing is offered in winter. Check Michigan''s current fish-consumption advisories for Lake St. Clair before eating your catch, and confirm current Michigan DNR fishing rules.","sourceUrl":"https://www.metroparks.com/lake-st-clair-metropark/"}'::jsonb, updated_at = now() WHERE slug = 'lake-st-clair-smallmouth';

UPDATE public.spots SET access = '{"boat":true,"ramp":"Bird Island Basin Boat Ramp, Padre Island National Seashore: paved ramp with small adjacent dock, gravel launch for paddle craft, and a small pier; the park''s only developed boat ramp, on the Laguna Madre","parking":"Dedicated trailer and single-vehicle spaces plus accessible spaces; vehicles must use a space designated for their type or may be cited or towed. Overflow parking is at Malaquite Visitor Center, about 4.3 miles away","facilities":["Accessible vault toilets","Fish-cleaning tables"],"notes":"The ramp is busy early in the morning, especially at weekends and holidays. A boat-ramp pass is required; it is sold at the entrance station, the visitor center or online through Recreation.gov. Check current Texas Parks and Wildlife fishing licence rules.","sourceUrl":"https://www.nps.gov/places/bird-island-basin-boat-ramp.htm"}'::jsonb, updated_at = now() WHERE slug = 'laguna-madre-redfish';

UPDATE public.spots SET access = '{"shore":true,"notes":"Drawienski National Park allows angling on the Drawa from Lake Dubie Poludniowe (Adamowo) to the bridge at the Kamienna power station from 1 January to 15 March and from 1 July to 31 December; Lakes Sitno and Ostrowieckie are open from 1 April to 30 November, and the park limits the number of anglers per day on each water. The only document entitling you to fish park waters is the park ticket (called a licence) together with an angler''s card and a catch register, sold through the park''s tourist information points or bilety.dpn.pl. On the Drawa only spinning and fly methods are allowed (fly hooks barbless); angling from floating equipment, ice fishing, groundbait and live or dead fish as bait on the Drawa are banned. Check the park''s current rules before you go.","sourceUrl":"https://dpn.gov.pl/wedkarstwo"}'::jsonb, regulations = '["Drawa National Park waters need the park''s own ticket (\"licence\") together with an angler''s card and catch register — check with the park about requirements for visitors","The park sets the open dates for the Drawa and its lakes and limits the number of anglers per day on each water","Fly and spinning methods only on the Drawa, with barbless hooks for fly; no angling from floating equipment"]'::jsonb, updated_at = now() WHERE slug = 'drawa-river-trout';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"The Main Inspectorate of Sea Fisheries (GIRM) issues recreational sea fishing rights by payment rather than a paper permit: weekly, monthly and annual options exist, validity starts on the day the payment is made, and you must carry an identity document and proof of payment. GIRM also requires some catches to be reported. Check the GIRM page for the current payment procedure and any catch-reporting duties before fishing.","sourceUrl":"https://www.gov.pl/web/girm/informacje-ogolne-nt-rybolowstwa-rekreacyjnego"}'::jsonb, updated_at = now() WHERE slug = 'baltic-coast-sea-trout';

UPDATE public.spots SET access = '{"shore":true,"notes":"Fish & Game describes good access along the length of the river and publishes an access map for Southland. The popular upper reaches are fishable from the bank or by an easy wade, and access there operates under a voluntary beat system to avoid overcrowding. Fish & Game encourages visiting anglers to check with local fishing shops. Check Fish & Game Southland for current access points and season dates.","sourceUrl":"https://www.fishandgame.org.nz/freshwater-fishing-in-new-zealand/where-to-fish/regional-info/southland/mataura-river/"}'::jsonb, regulations = '["Fish & Game Southland or national licence required","Seasons differ by section: the river is open year-round below Mataura Island Bridge and the season is extended below Gore — check Fish & Game Southland for current dates on the upper river","No felt-soled boots; check and dry gear to prevent didymo"]'::jsonb, updated_at = now() WHERE slug = 'mataura-river';

UPDATE public.spots SET access = '{"boat":true,"notes":"Queenstown Lakes District Council requires a boat ramp permit for each trailer launched on Lake Wanaka and Lake Hawea. Permits are sold at the council offices in Queenstown and Wanaka and must be displayed on the trailer. Check the council''s Navigation Safety Bylaw for current boating rules.","sourceUrl":"https://www.qldc.govt.nz/recreation/lakes-and-boating/boat-ramp-permit-fees"}'::jsonb, updated_at = now() WHERE slug = 'lake-wanaka-trout';

UPDATE public.spots SET access = '{"boat":true,"notes":"The Marlborough Sounds blue cod fishery is closed to taking blue cod from 1 September to 10 January inclusive, a season extended by MPI to let the fishery recover. MPI asks anglers to target other species away from rocky-reef blue cod habitat during the closure and to minimise handling and use large circle hooks when blue cod are caught. Check MPI and the NZ Fishing Rules app for current rules and closed areas.","sourceUrl":"https://www.mpi.govt.nz/fishing-aquaculture/recreational-fishing/fishing-rules/challenger-fishing-rules/do-not-disturb-give-marlborough-sounds-blue-cod-the-best-chance-to-recover"}'::jsonb, regulations = '["No licence required for recreational sea fishing","Blue cod cannot be taken from 1 September to 10 January inclusive in the Marlborough Sounds — check Fisheries NZ for current rules before fishing","Some areas are closed or restricted to protect the blue cod fishery"]'::jsonb, updated_at = now() WHERE slug = 'marlborough-sounds-blue-cod';

UPDATE public.spots SET access = '{"shore":true,"notes":"Fish & Game describes an abundance of easy access to the main river and all tributaries, less than an hour''s drive from Nelson, and publishes a Motueka River Access Guide (updated February 2024) for access points. The catchment, including tributaries such as the Wangapeka, Baton and Motupiko, is protected by a Water Conservation Order. Check Fish & Game Nelson/Marlborough for current season dates and licence rules.","sourceUrl":"https://www.fishandgame.org.nz/freshwater-fishing-in-new-zealand/where-to-fish/regional-info/nelson-marlborough/motueka-catchment/"}'::jsonb, updated_at = now() WHERE slug = 'motueka-river';

UPDATE public.spots SET access = '{"boat":true,"ramp":"South Bay Marina, southern side of the Kaikoura Peninsula: slipway with seawall","parking":"Parking for buses, cars, trailers and boats at the marina","facilities":["Public toilet","Fuel","Boat wash-down area"],"notes":"A recreational slipway fee applies at South Bay; the Kaikoura District Council sets the current fee and runs a pay-and-display machine at the slipway. The Environment Canterbury Harbourmaster can be contacted on 0800 324636 or 03 319 5781 about boating queries.","sourceUrl":"https://www.kaikoura.govt.nz/community/community-facilities/airport-harbour-wharfs"}'::jsonb, updated_at = now() WHERE slug = 'kaikoura-offshore';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"Fish & Game''s Eastern region describes thirteen lakes open to fishing in the Rotorua district with both shoreline and boat fishing, and publishes angler-access brochures for individual lakes. Lake Okataina is under an MPI Controlled Area Notice: boats must first be washed at The Wash Place, 338 Te Ngae Rd, Rotorua, and a PIN issued after the online form opens the automated gate at the lake. Any boat that has been in the Waikato River in the previous 30 days must be cleaned at a designated wash station before entering other Rotorua lakes, in addition to Check Clean Dry. Confirm current biosecurity requirements before launching.","sourceUrl":"https://www.fishandgame.org.nz/freshwater-fishing-in-new-zealand/where-to-fish/regional-info/eastern/"}'::jsonb, updated_at = now() WHERE slug = 'rotorua-lakes-trout';

UPDATE public.spots SET access = '{"boat":true,"notes":"The Environment Agency notes that the public right of navigation on the Wye does not give an absolute right of access to the riverbank downstream of Hay Bridge (except in an emergency): get the landowner''s permission before launching or landing a boat, and before camping or picnicking on the banks. There is no confirmed legal right of navigation upstream of Hay Bridge. Fishing also needs the permission of the controlling club or landowner. Check Environment Agency guidance for current river conditions and restrictions.","sourceUrl":"https://www.gov.uk/guidance/information-to-help-boaters-on-the-river-wye"}'::jsonb, updated_at = now() WHERE slug = 'river-wye-barbel';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"The Broads Authority lists several publicly accessible fishing platforms and permits angling from most of its 24-hour moorings unless signed otherwise; anglers must give way to boats wishing to moor and keep paths clear. You may fish from a stationary boat but not from a moving boat (trolling) unless it is being rowed. Stretches managed by angling clubs and private land need the owner''s or club''s permission, so watch for signage. The Authority advises against fishing for pike in summer when water temperatures are high. An angling access map of the fishing platforms is published by the Authority.","sourceUrl":"https://www.broads-authority.gov.uk/looking-after/managing-land-and-water/recreation-and-tourism/angling"}'::jsonb, regulations = '["Environment Agency rod licence required","Coarse fish close season (15 March to 15 June inclusive) applies on the Broads waterways; it does not apply to some private stillwaters and fisheries — check the Environment Agency Anglian byelaws","Use wire traces and unhooking mats — pike welfare rules are enforced locally"]'::jsonb, updated_at = now() WHERE slug = 'norfolk-broads-pike';

