-- Verified access details — batch 4: Florida Keys, Louisiana, Norway, France,
-- Spain, Germany, Mexico (2026-07-29)
--
-- Same discipline as batch 3: only fields the recorded sourceUrl actually
-- supports. Licence and permit regimes are described rather than priced, and no
-- bag or size numbers are recorded.
--
-- Note on Islamorada: the Village's own Founders Park page is signed "No
-- Fishing", and the boat ramp widely attributed to Founders Park by guide sites
-- is in fact the Village ramp at Plantation Yacht Harbor Marina. The record
-- below follows the Village page, not the guide sites.

UPDATE public.spots SET access = '{"shore": true, "boat": true, "ramp": "Public boat ramp at the Village-run Plantation Yacht Harbor Marina, staffed daily 8am to 6pm", "parking": "Dedicated trailer parking at the marina", "facilities": ["Boat ramp", "Fuel (unleaded and diesel)", "Sewage pump-out", "Showers", "Coin laundry", "Water and electricity at slips", "Wi-Fi"], "notes": "Launching is free for Village of Islamorada residents on production of valid ID; non-residents pay a launch fee in each direction, so a round trip is charged twice. The ramp is only attended within marina hours. Note that Founders Park itself is signed no-fishing — the Village ramp is at the marina.", "sourceUrl": "https://www.islamorada.fl.us/286/Plantation-Yacht-Harbor-Marina"}'::jsonb, updated_at = now() WHERE slug = 'islamorada-tarpon-flats';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Anglers aged 18 and over need a Louisiana saltwater licence to fish recreationally south of the state''s saltwater line, which covers the delta. Offshore species — tunas, billfish, swordfish, amberjacks, snappers, groupers, cobia, wahoo, dolphinfish and gray triggerfish among them — additionally require a Recreational Offshore Landing Permit, though anglers on a paid for-hire charter are covered by the operator. Buy licences through the LDWF before travelling.", "sourceUrl": "https://www.wlf.louisiana.gov/page/recreational-fishing-licenses-and-permits"}'::jsonb, updated_at = now() WHERE slug = 'venice-louisiana-redfish';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Sea angling in Norway needs no fishing licence and is open to everyone, but the Directorate of Fisheries sets conditions: handheld tackle only, and species that can only legally be taken with other gear are off limits. Selling your catch is illegal, and you must stay more than 100 metres from the nearest fish farm. Export of fish out of Norway is capped, with a larger allowance only for anglers fishing through a registered tourist fishing business that reports catches — the limits are periodically reduced, so check the current figure before travelling. Anyone born in or after 1980 needs a boating licence for vessels of 8 to 15 metres or engines over 25hp.", "sourceUrl": "https://www.fiskeridir.no/english/sea-angling-in-norway/regulations"}'::jsonb, updated_at = now() WHERE slug = 'lofoten-skrei-cod';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Under the French Code de l''environnement, fishing in fresh water requires membership of an approved local association (AAPPMA), which is what a carte de pêche represents — there is no separate government licence. Cards are sold online at cartedepeche.fr and cover the year, a week or a single day, so short visits are straightforward. An interfederal card widens access beyond the home department, which matters on a river as long as the Loire.", "sourceUrl": "https://www.cartedepeche.fr/"}'::jsonb, updated_at = now() WHERE slug = 'loire-river-catfish';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Fishing the Ebro at Mequinenza requires the Aragón regional licence, compulsory from age 14 and issued by the Instituto Aragonés de Gestión Ambiental (INAGA) online or in person. No separate coto permit applies to the Mequinenza reservoir — the regional licence alone is enough. Aragón republishes its Plan General de Pesca each year in the Boletín Oficial de Aragón, and that document, not the licence, defines which waters are open, the cotos, closed areas and catch-and-release stretches, so check the current edition before fishing.", "sourceUrl": "https://www.aragon.es/tramitador/-/tramite/solicitud-licencia-pesca-1"}'::jsonb, updated_at = now() WHERE slug = 'ebro-mequinenza-catfish';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Germany sets a high bar for visiting anglers. Baden-Württemberg requires a state Fischereischein, which must be carried while fishing and is issued only after a 32-hour course and an examination — it cannot be bought on arrival. On top of that you need an Erlaubnisschein (day ticket) from whoever holds the fishing rights on the specific stretch, and on many Karlsruhe waters those tickets are limited or restricted to club members. Plan this well ahead; the legal basis is the Fischereigesetz für Baden-Württemberg and the Landesfischereiverordnung.", "sourceUrl": "https://lfvbw.de/angelfischerei/wie-werde-ich-angler/"}'::jsonb, updated_at = now() WHERE slug = 'rhine-karlsruhe-carp';

UPDATE public.spots SET access = '{"boat": true, "notes": "Mexico requires an individual CONAPESCA sportfishing permit, and it applies to every person aboard the vessel, not only those holding a rod. Permits are issued to nationals and foreign visitors alike for a day, a week, a month or a year, are non-transferable and cannot be extended, and are paid for through the federal E5CINCO system. Reputable lodges and guides normally arrange them, but confirm this when booking.", "sourceUrl": "https://conapesca.gob.mx/wb/cona/permiso_de_pesca_deportiva"}'::jsonb, updated_at = now() WHERE slug = 'ascension-bay-bonefish';

UPDATE public.spots SET access = '{"boat": true, "notes": "Mexico requires an individual CONAPESCA sportfishing permit, and it covers every person aboard the boat whether or not they fish — a common surprise for families joining a charter. Permits run for a day, a week, a month or a year, are issued to visitors as well as residents, and are non-transferable. Charter operators usually include them, but check before sailing.", "sourceUrl": "https://conapesca.gob.mx/wb/cona/permiso_de_pesca_deportiva"}'::jsonb, updated_at = now() WHERE slug = 'cabo-san-lucas-marlin';

UPDATE public.spots SET access = '{"boat": true, "notes": "Mexico requires an individual CONAPESCA sportfishing permit for everyone aboard the vessel, not just the anglers. Permits are available to foreign visitors for a day, a week, a month or a year, are individual and non-transferable, and are paid through the federal E5CINCO system. Most panga and charter operators handle the paperwork — confirm it is included.", "sourceUrl": "https://conapesca.gob.mx/wb/cona/permiso_de_pesca_deportiva"}'::jsonb, updated_at = now() WHERE slug = 'la-paz-roosterfish';
