-- Verified access details — Bay of Islands, Müritz, Brittany, Gibraltar, Po (2026-07-29)
--
-- Sources: Far North District Council, Fisheries New Zealand (MPI), LALLF M-V,
-- Fischerei Müritz-Plau GmbH (the leaseholder LALLF designates as permit
-- issuer), DIRM Nord Atlantique-Manche Ouest, ARS Bretagne, the Spanish BOE,
-- and the Emilia-Romagna and Lombardy regional fisheries pages.
--
-- Health advisories: checked for all five. Found and recorded for Brittany
-- (ARS Bretagne shellfish monitoring). NOT recorded for the Po: the widely
-- repeated claim that Po catfish carry unsafe mercury traces only to
-- unofficial write-ups of a 2012 study, with no advisory from the Ministero
-- della Salute, ARPA or a local ASL that could be cited. Official page or NULL.

UPDATE public.spots SET access = '{"shore": false, "boat": true, "ramp": "Far North District Council maintains the public ramps and lists them for the Bay of Islands at Ōpito Bay, Rangitāne, Rangitoto (Windsor Landing), Rāwhiti, Russell, Tapeka Point, Te Haumi, Waipapa Landing and Waitangi.", "parking": "The council publishes ramp capacity, access and car parking detail per location on its Maritime Facilities pages rather than in one table — check the ramp you plan to use.", "notes": "Marlin are taken offshore, so this is a game-boat fishery rather than a land-based one; the ramps above are the launching points, not the fishing grounds. LICENCE: no licence is needed to fish in the sea anywhere in New Zealand — the licence requirement applies only to fresh water. Rules differ across the seven fishing areas and Fisheries New Zealand publishes them in the free NZ Fishing Rules app. Selling or trading a recreational catch is illegal. RĀHUI — THIS ONE CATCHES VISITORS OUT: Maunganui Bay, which includes Deep Water Cove in the southern Bay of Islands, has been closed to all fishing except the gathering of kina since 2010. The closure is made under section 186A of the Fisheries Act 1996 on the application of Ngāti Kuta and Patukeha ki Te Rāwhiti as mana whenua, and is renewed in two-year periods, so it is a live restriction rather than a historical one. Breaching it carries a fine of up to NZ$100,000. Diving, swimming and anchoring in the bay are unaffected — it is the taking of fish and shellfish that is prohibited. Check current rules and closures before fishing.", "sourceUrl": "https://www.fndc.govt.nz/Facilities/Maritime-Facilities-in-the-Far-North/bay-of-islands-boat-ramps"}'::jsonb, updated_at = now() WHERE slug = 'bay-of-islands-marlin';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "PERMITS — three separate documents, which trips up most visitors. You need (1) a Fischereischein, or the Touristenfischereischein, which is valid for 28 consecutive days across Mecklenburg-Vorpommern and costs EUR 24; (2) the M-V Fischereiabgabe fee stamp, EUR 10, required even if your Fischereischein was issued by another German state; and (3) an Angelerlaubnis for the specific water. LALLF, the state fisheries authority, issues coastal permits itself but for inland waters like the Müritz the permit comes from the owner or leaseholder. That is Fischerei Müritz-Plau GmbH, trading as Müritzfischer, whose cards cover nearly 80 waters in the Müritz system. Tourist licence, fee stamp and cards are all available at the Waren (Müritz) tourist information office, and online at erlaubnis.angeln-mv.de. CARD TYPE MATTERS: a shore card (Uferangeln) permits fishing only from the bank and structures such as jetties — you need a combination card to fish from a boat or belly boat. Night fishing is allowed from one hour after sunset to one hour before sunrise, from the shore or an anchored boat, with the motor off. LOCAL RESTRICTIONS: all fishing is banned at the Wünnow near Röbel from 15 February to 15 July; artificial lures, including trolling and drift fishing, are banned from 1 April to 1 June on the Kleine Müritz and named connected waters; keep 200 m clear when fishing near the Vipperow road bridge and 100 m either side of the Malchow swing bridge. Check the current Angelregeln before you travel.", "sourceUrl": "https://www.mueritzfischer.de/angeln/angelregeln/"}'::jsonb, updated_at = now() WHERE slug = 'mueritz-lakes-pike';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "LICENCE: recreational sea fishing in France needs no licence, from the shore or a boat. Selling or buying the catch is strictly forbidden — it is reserved for the angler and their family. MARKING: regulated species must be marked at the moment of capture by removing the lower lobe of the caudal fin. For boat fishing that means as the fish comes aboard, for shore-based spearfishing on returning to the shore, and for shore rod fishing at capture. DECLARATION: five sensitive species — sea bass, pink dentex, pollack, mackerel and bluefin tuna — must be declared through the RecFishing app within 24 hours of capture, whether you keep the fish or release it. SEA BASS: the rules are reset annually and include a late-winter window in which retention is prohibited and only catch-and-release is allowed — in 2026 that ran from 1 February to 31 March. Because the dates move every year, read the current synthesis published by DIRM Nord Atlantique-Manche Ouest before a trip. HEALTH ADVICE: ARS Bretagne monitors around 100 of the most-used recreational shellfish-gathering sites on the Breton coast and rates each from authorised through tolerated and discouraged to prohibited. At 1 January 2025, of 98 sites monitored, gathering was authorised or tolerated at 36, discouraged at 45 and prohibited at 17, mostly because of toxic microalgae and bacterial contamination. The agency publishes a live map at pecheapied-responsable.fr. That applies to shellfish rather than to bass, but it is worth checking if you gather bait or shellfish on the same tide. Check current rules before fishing.", "sourceUrl": "https://www.dirm.nord-atlantique-manche-ouest.developpement-durable.gouv.fr/peche-de-loisir-en-bretagne-synthese-de-la-a1104.html"}'::jsonb, updated_at = now() WHERE slug = 'brittany-sea-bass';

UPDATE public.spots SET access = '{"shore": false, "boat": true, "notes": "CATCH AND RELEASE ONLY: recreational bluefin tuna fishing in Spain is permitted in one form only — pesca sin muerte, fishing without killing. Recreational and sporting competitions or events aimed at killing bluefin are prohibited outright. AUTHORISATION: beyond the general recreational sea fishing licence, a specific bluefin authorisation is required, applied for through PescaREC, the free mobile app published by the Ministry of Agriculture, Fisheries and Food. The authorisation must be aboard the vessel while fishing. SEASON: the recreational fishery set for 2026 opens on 16 June and closes on 14 October, or earlier if the quota is used up — PescaREC shows the real-time open or closed status of the fishery. REPORTING: prior notice of arrival and a declaration are both mandatory, and the declaration must be filed within 24 hours of finishing, covering released fish as well as retained ones. FOREIGN-FLAGGED BOATS: an authorisation issued to a non-Spanish flagged vessel permits catch and release only — retaining or landing bluefin is prohibited under any circumstance. In practice this makes a licensed charter out of the Strait ports the normal route. The terms are reset each year by a resolution of the Secretaría General de Pesca published in the BOE, so check the current one before booking.", "sourceUrl": "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-12503"}'::jsonb, updated_at = now() WHERE slug = 'strait-of-gibraltar-tuna';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "LICENCE: Italy issues recreational freshwater licences regionally, and the type B licence is little more than a tax receipt. In Lombardy it consists solely of the receipt for the EUR 23 annual regional concession tax, valid for 12 months from payment and recognised across Italy; carry it with photo ID. Residents under 18 or over 65, and people covered by Law 104/1992 who fish only with rod and reel, are exempt. In Emilia-Romagna the type B licence is the receipt for a EUR 22.72 concession tax, also valid nationwide for a year and also shown with ID. WHICH RULES APPLY: the detail — seasons, permitted methods, protected stretches — is set regionally and published in each region''s Calendario ittico. Emilia-Romagna works from Regional Law 11/2012 and Regional Regulation 1/2018; Lombardy publishes basin handbooks, and the Po main stem is Bacino 2. The Po is coordinated across Lombardia, Emilia-Romagna, Piemonte, Veneto and the Autorità di bacino del fiume Po under a joint protocol, but the rules you fish under still depend on which region and which bank you are standing on, so check the Calendario ittico for that stretch. Check current rules before fishing.", "sourceUrl": "https://agricoltura.regione.emilia-romagna.it/pesca/pesca-sportiva-professionale-acque-interne"}'::jsonb, updated_at = now() WHERE slug = 'po-river-catfish';
