-- Verified access details — batch 3: NZ, Nordics, Italy, Poland, South Africa (2026-07-29)
--
-- Only fields traceable to the recorded sourceUrl are populated; ramp, parking,
-- walkIn and facilities are left absent wherever the official page does not name
-- them. Fees and bag limits are deliberately described rather than quoted, since
-- both go stale.

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "The Taupō district has its own DOC-issued licence — Fish & Game New Zealand licences are not valid here. There is no closed season, and the licence year runs 1 July to 30 June. Shore anglers work the long sandy bays, rocky headlands and stream mouths, where trout concentrate. Dinghies and kayaks suit calm weather only and are best kept to the sheltered bays west of Taupō and Tūrangi; the lake is large, exposed and its weather turns quickly. Take care wading at river mouths, where steep pumice drop-offs shelve away sharply underfoot.", "sourceUrl": "https://www.doc.govt.nz/parks-and-recreation/places-to-go/central-north-island/places/taupo-trout-fishery/where-to-fish/lake-taupo/"}'::jsonb, updated_at = now() WHERE slug = 'lake-taupo-trout';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Finland''s everyman''s right covers simple rod-and-line fishing free of charge. Lure fishing, spinning and trolling need the national fisheries management fee for anyone aged 18 to 69, and on state-owned water a Metsähallitus permit as well — both are sold online at eraluvat.fi. Permits are area-specific, so check the permit area covers the part of the lake you intend to fish.", "sourceUrl": "https://www.eraluvat.fi/en/fishing/fishing-permits"}'::jsonb, updated_at = now() WHERE slug = 'saimaa-pike-zander';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Rod fishing for salmon requires the joint Metsähallitus permit for the Tornionjoki, Muonionjoki and Könkämäeno, bought either for the whole border river or for a single sub-area — Tornio, Ylitornio, Pello, Kolari, Muonio or Enontekiö. Permit holders have extensive bank fishing along the river. The traditional boat method is rowed trolling; motorboats are allowed in the marked navigation channels, and the rower needs a permit too. The salmon rod season runs from early June to late August under the Finland-Sweden transboundary Fishing Rule, with a weekly closed period from Sunday 7pm to Monday 7pm Finnish time. Under-15s do not need a permit. Permit boundaries are mapped at infogis.fi/tornionjoki.", "sourceUrl": "https://eraluvat.fi/en/fishing/fishing-permits/angling-permit/alueet/tornionjoki-muonionjoki-konkamaeno.html"}'::jsonb, updated_at = now() WHERE slug = 'tornionjoki-salmon';

UPDATE public.spots SET access = '{"boat": true, "notes": "There is no open public access. The Alta is managed by Alta Laksefiskeri Interessentskap (ALI) and rods are allocated by ballot, because demand far exceeds the water available. Two draws are held — one for local anglers around the end of February, one for non-local anglers in early March — and the river is divided into five zones carrying different numbers of rods. The early June weeks are reserved for local anglers, with successful outside applicants fishing from mid-July. Fishing is largely from boats with a local rower, and trips are booked far in advance.", "sourceUrl": "https://visitalta.no/en/article/the-dream-of-every-salmon-fisher/"}'::jsonb, updated_at = now() WHERE slug = 'alta-river-salmon';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Lake Garda spans three administrative regions — Trentino to the north, Lombardy to the west and Veneto to the east — and each licences fishing separately, so which permit you need depends on the shore you fish. In Trentino, visitors without a licence from their own region of residence need the Trentino tourist fishing licence, which replaces the government licence and runs 30 consecutive days; day and area permits are issued by local angling associations. Confirm the rules for the specific stretch before fishing.", "sourceUrl": "https://www.visittrentino.info/en/articles/summer-mountain-holidays/fishing-tourist-licence"}'::jsonb, updated_at = now() WHERE slug = 'lake-garda-trout';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Poland''s flowing waters, the Vistula included, are state-owned and managed by the Polish Angling Association (PZW). Fishing requires a permit issued for the relevant PZW district (okręg), so the permit depends on the stretch — the Warsaw district covers the Mazovian reaches. Permits are sold online and through tackle shops as day or season tickets, at separate rates for PZW members and non-members. Each permit lists the waters it covers.", "sourceUrl": "https://www.pzw.org.pl/home/"}'::jsonb, updated_at = now() WHERE slug = 'vistula-river-zander';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "The Masurian lakes fall across PZW districts in the Warmian-Masurian and Podlaskie voivodeships, and a permit entitles you to fish only the lakes on that district''s published list — so match the permit to the specific lake. Day and season e-permits are sold online, at separate rates for PZW members, non-members and foreign visitors.", "sourceUrl": "https://zezwolenia.pzw.suwalki.pl/index.php?krok=zezwolenie&lang=EN"}'::jsonb, updated_at = now() WHERE slug = 'masurian-lakes-pike';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Shore angling at Cape Point sits inside the Table Mountain National Park Marine Protected Area, and two permits are needed: a DFFE recreational fishing permit, issued through South African Post Office branches, and a SANParks My Activity Permit at the line-fishing level, bought online and valid 12 months from purchase. The activity permit also exempts the holder from park entrance fees at pay points when fishing. The MPA contains six restricted areas, five of them no-take zones where fishing is prohibited, so check the zone boundaries before casting.", "sourceUrl": "https://www.sanparks.org/parks/table-mountain/cards-permits/marine-species-access-permit"}'::jsonb, updated_at = now() WHERE slug = 'cape-point-yellowtail';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "Sodwana Bay lies inside the iSimangaliso Wetland Park, so park gate entry fees and a community conservation levy apply per person and per vehicle, on top of any fishing permit. Launching a vessel requires a launch permit paid at the park, and charter fishing is covered by a separate activity permit. Tariffs are reviewed periodically — confirm current rates with the park before travelling.", "sourceUrl": "https://www.isimangaliso.com/blog-details/gate-tariffs-and-activity-permits-price-increase/"}'::jsonb, updated_at = now() WHERE slug = 'sodwana-bay';
