-- Verified access details — batch 11
--
-- 17 spot(s) with records, 37 skipped. Every sourceUrl is an official
-- government, park-authority, council or fisheries-body page (CLAUDE.md content rules 1-3).
-- Apply by hand in the SQL Editor, then rebuild (migration first, then build).
--
-- ruegen-baltic-sea-trout: LALLF M-V (Landesamt fuer Landwirtschaft, Lebensmittelsicherheit und Fischerei, the state fisheries authority) Fischereidokumente page: three documents are always required in Mecklenburg-Vorpommern coastal waters (Fischereischein, Angelerlaubnis and proof of the state Fischereiabgabe); the coastal waters are the Bodden, Haffe, Peenestrom, Achterwasser and the Baltic within German territorial waters; the page states there are no free angling waters in MV; tourist licence valid up to 28 days. Existing regulations ("Fischereischein plus a coastal fishing permit") were right but omitted the Fischereiabgabe; line extended. No ramp or shore-access detail found on an official page.
--
-- sylt-north-sea: Nationalpark Wattenmeer (Schleswig-Holstein Wadden Sea National Park authority) page on recreational angling: angling is generally possible in the coastal strip except in marked breeding and resting sites in salt marshes; boat angling is possible almost everywhere in the park except the usage-free zone south of the Hindenburgdamm. Existing regulations (Fischereischein required; national-park restrictions) are consistent. I did NOT claim that the prohibited boat zone includes Sylt: the page does not say so. Notes-only record.
--
-- sete-mediterranean-tuna: French Ministry of the Sea (mer.gouv.fr) page "Pratiquer la peche de loisir au thon rouge": annual authorisation from the regional maritime directorate (DIRM) is required to fish bluefin tuna recreationally in the East Atlantic and Mediterranean from a French-flagged or EU-registered recreational/charter vessel; third-country-flag vessels are prohibited; a retained tuna must be tagged immediately; landings must be declared to FranceAgriMer within 48 hours. Existing regulations already mention authorisation and tag; this adds the who/how. One-per-vessel figure from the page deliberately not repeated (bag-number rule 3). No port/ramp detail for Sete found on an official page, so notes-only.
--
-- normandy-bass-cotentin: French Ministry of the Sea (mer.gouv.fr) page "Peche de loisir en mer": the page mentions no licence requirement (existing "no licence" line kept); shore anglers must respect minimum sizes and closures, leave no waste on the foreshore and tell someone where they are going; recreational fishers aged 16+ targeting designated sensitive species, including sea bass in the Channel and Bay of Biscay zones, must register annually through the RecFishing app and declare catches daily; catches are marked by removing the lower part of the tail fin; shellfish sanitary zone maps exist. CONTRADICTION FIXED: existing regulations listed only "no licence" and size/bag limits and missed the registration and marking duties, which a reader could be fined for ignoring; line added. No specific Cotentin ramp or rock-mark access page found (manche.gouv.fr pages errored in the browser), so notes-only.
--
-- sicily-bluefin-tuna: Egadi Islands Marine Protected Area management body (ampisoleegadi.it, run under the Comune di Favignana and the Italian environment ministry), zoning page, read via WebFetch and cross-checked with a search summary of the same page: sport fishing is listed only for zones B and C and is subject to authorisation; spearfishing is banned throughout the MPA; zone A is the integral reserve; zone D is the protection zone between the islands. The two summaries differed on whether zone C also needs authorisation, so the record says authorisation applies and points to the MPA body for the procedure. Existing regulations (MASAF registration, RecFishing, bluefin authorisation) are unchanged; the national bluefin nulla-osta detail from the Guardia Costiera was not added because it is a different page.
--
-- canary-islands-marlin: Gobierno de Canarias fisheries department page on recreational maritime fishing licences, read via WebFetch (Spanish): three licence classes (class 1 surface trolling from vessels, class 2 spearfishing, class 3 surface fishing from land or vessels without trolling), valid three years, issued through the regional electronic office; marlins, tunas, swordfish and hake are "species under differentiated protection" that need a separate authorisation requested from the national Ministry of Agriculture, which keeps management and control. Existing regulations (licence, billfish released, authorisations may apply) consistent; the class and the national authorisation route are the additions.
--
-- costa-brava-spinning: Generalitat de Catalunya, Parcs Naturals page "Activitats a mar" for the Cap de Creus Natural Park (Girona coast), summarised via WebFetch: recreational fishing is allowed in the marine part of the park with a special park permit obtained after training, in addition to the general licence; daily catch reporting and marking; only catch-and-release in the coves of Murtra, Caials and Tamariua; fishing banned in the S'Encalladora integral reserve. Two separate summaries of the park rules disagreed about the partial reserves, so nothing is stated about them. The spot description was not checked against Cap de Creus: the record is written as applying to fishing INSIDE the park and says so. CONTRADICTION FIXED: existing regulations said marine protected areas along this coast are "no-take", which is too broad (the park allows permitted fishing outside its integral reserve); reworded to "some".
--
-- hardangerfjord-sea-trout: HEALTH ADVISORY. Same Mattilsynet page as oslofjord-sea-trout: for Hardangerfjord/Sorfjorden (contaminated with cadmium, lead, mercury, dioxins and PCB) it lists several restrictions: avoid brosme (tusk) and pollock in specified zones, pregnant and nursing women to avoid crab, lobster and stationary fish in the inner areas, and shellfish restrictions in designated zones. The page does not list sea trout, so nothing is claimed about it, and the exact zones were not read, so the record points to the page for them. Advisory-only record; no access page found.
--
-- oslofjord-sea-trout: HEALTH ADVISORY. Mattilsynet (Norwegian Food Safety Authority) page "Unngaa fisk og skalldyr fra forurensede havner, fjorder og innsjoer", read via WebFetch: for inner Oslofjord (inside Drobak) it advises pregnant and nursing women and children under 5 not to eat cod fillet because of mercury, and the general population to avoid mussels from the inner harbour area because of PAH. The page does not list sea trout, so no claim is made about it. No access/ramp page found; this is an advisory-only record, which is the useful part.
--
-- vattern-char: HEALTH ADVISORY. Livsmedelsverket (Swedish Food Agency) page "Fisk som kan innehalla miljogifter", read in a real browser, last reviewed 2025-09-23: wild-caught char (roding) from Vattern, and wild trout, whitefish and salmon from Vattern, can contain high levels of dioxin and PCB; children, young people, people who are pregnant, breastfeeding or planning pregnancy should eat them at most 2-3 times a year, others can eat them about once a week; eel should not be eaten at all. Existing regulations unchanged; advisory-only record (no ramp/parking detail from an official page).
--
-- bohuslan-coast-mackerel: Lansstyrelsen Vastra Gotaland (county administrative board) "Fiske" page, read via WebFetch (Swedish): sea fishing with hand-held gear is free; from 1 January to 31 March fishing for cod is prohibited inside the trawl boundary; fishing for cod is prohibited all year in the Gullmarsfjorden protection area; from 1 October to 31 March fishing is prohibited in all protected areas (fredningsomraden); maps are on Svenska Fiskeregler. The page's size minimum for cod is deliberately NOT repeated (content rule 3). Existing regulations (free unlicensed rod fishing, cod restricted, sea trout closures near river mouths) consistent; the dated closures are the additions.
--
-- vindelalven-grayling: Lansstyrelsen Vasterbotten (county administrative board) page "Ansok om fiske i kvoterade vatten", read via WebFetch (Swedish): Vindelalven from Mankeforsen to Sarngejukkes is quota-managed; permits are allocated by lottery, applications open 1 January to 30 April with results from the second half of May; up to five fishing days can be applied for on the Vindelalven; fly fishing with a fly rod only on most quota waters; catch reporting is mandatory; the season is 1 July to 20 August on the Vindelalven. Catch-number and size-window details on the page are deliberately NOT repeated (content rule 3). CONTRADICTION FIXED: existing regulations said only "a local fiskekort is required", which would send an angler to buy a card for a stretch where a lottery permit is needed.
--
-- gotland-sea-trout: Two official sources. (1) Lansstyrelsen Gotland (county administrative board) "Fiske" page, read via WebFetch: sea trout protected 1 Sept-31 Jan in 25 protected areas at 34 watercourses, from 2025 also within the watercourses themselves; pike and perch protected 1 Mar-31 May in coastal waters out to 4 nautical miles around all of Gotland; free handheld-tackle fishing in coastal waters. (2) Livsmedelsverket (Swedish Food Agency) advice page, read in a real browser: wild trout from the Baltic can contain high dioxin and PCB levels (HEALTH ADVISORY). CONTRADICTION/GAP FIXED: existing regulations mentioned only river-mouth protection zones and sea trout size; the pike/perch coastal closure was missing and the protection now extends into the watercourses. The record carries one sourceUrl (the county board), so the Food Agency advisory (Baltic trout) is NOT written into the record; a follow-up could add it once the record shape allows a second source.
--
-- inari-lake-trout: Metsahallitus (Finnish state land manager) Eraluvat permit-shop page for angling permit area 1504 Inarijarvi, read via WebFetch: covers Lake Inarijarvi and Lake Nitsijarvi; the angling permit is specific to the boating party (one valid permit per boat); the number of permits is limited; fisheries management fee applies to lure anglers aged 18-69; hook-and-line and ice fishing with one rod are free. Prices deliberately not stated. Existing regulations (management fee plus regional permit) consistent; the regional fishing-area rules were not read.
--
-- kymijoki-river: Metsahallitus Eraluvat page for angling permit area 7581 Langinkoski (Kymijoki, Kotka), read via WebFetch: lowest rapids of the Langinkoski branch inside the Langinkoski nature reserve near Kotka centre; fly fishing only; hook-and-line and ice fishing prohibited; maximum eight anglers at once; native fish (adipose fin intact) must not be kept; season 1 Jan-30 Sept and 1-31 Dec; permit plus fisheries management fee. The spot is described only as the River Kymijoki, so the record is written as "at Langinkoski" and says so. Existing regulations (beat permit, catch-and-release, hydro releases) consistent.
--
-- ruunaa-rapids: Metsahallitus Eraluvat page for permit area 7525 Ruunaan kosket (Finnish), read via WebFetch: stretch from Paasikoski to below Siikakoski including Murroojarvi and Kattilajarvi; allowed methods; wading prohibited 1 Sept-31 May; fishing banned in the Paasikoski-Mutikaisenkari section 1 Sept-30 Nov; Kattilakoski run as a reserved rapid for group bookings; rod permit plus fisheries management fee; open all year. The page title for the permit was summarised as a free rod permit, so the record says "rod-fishing permit" only. Existing regulations consistent; the seasonal no-wading and closed-section dates are the additions.
--
-- vuoksi-river-trout: City of Imatra (local authority) page "Vuoksen kalastusalueet ja lupaehdot", read via WebFetch: Vuoksi (excluding Mellonlahti) and Mellonlahti need different permits; fly fishing, spinning and trolling allowed; bait and ice fishing allowed without a Vuoksi permit; motor trolling restricted to the stretch Kyyronkoski to the border zone; all fishing prohibited 15 Oct-15 Nov between the railway bridge and the river mouth; grayling protected 1 Apr-31 May. The page did not address Saimaa salmon release (already in existing regulations) and did not say where permits are bought, so neither is stated.
--
-- Not included this batch:
-- - isar-bavaria-trout: Official Bavarian sources (StMELF, Bezirk Oberbayern fisheries advisory) give only the statewide Fischereischein plus Erlaubnisschein rule; nothing specific to the Isar at Lenggries (beats, access points). Repeating a statewide rule across several spots would be template filler, not verified access detail.
-- - bodensee-whitefish: IBKF (the international fisheries commission) home page carries no angler-access detail; the Baden-Wuerttemberg permit card is a PDF not readable here. Only statewide licence/permit rules available, already in the existing regulations.
-- - mueggelsee-berlin: Berlin Fischereiamt pages cover the Fischereischein/Angelkarte/Fischereiabgabe system generally; none carries Muggelsee-specific access, ramp or parking detail. Existing regulations are consistent with them.
-- - danube-bavaria-catfish: Same as isar-bavaria-trout: only statewide Bavarian licence rules found on official pages; no Danube/Deggendorf access or ramp page.
-- - wiesent-franconia-trout: Same as isar-bavaria-trout: no Wiesent-specific official page found (Bezirk Oberfranken fisheries advisory not checked to a readable page in this pass).
-- - dordogne-river-barbel: Only EDF (utility) and Correze prefecture PDFs found for dam releases; EDF is not a government source and the prefecture order is an unreadable PDF. The dam-release hazard is already in the existing regulations.
-- - gave-de-pau-salmon: NOT RESEARCHED in this pass.
-- - lake-annecy-char: Haute-Savoie prefecture pages errored in the browser; the prefectoral fishing order (DDT-2023-1579) and the SILA PCB/PAH contamination study exist but are PDFs not readable here. A char consumption advisory likely exists (an earlier prefectoral ban was reported in search results) but was not verified on a readable official page, so nothing is stated. Worth a follow-up with a PDF reader.
-- - rhone-river-catfish: Search returned VNF/CNR corporate and fishing-access press pages for other sections (Haut-Rhin); nothing on the Avignon stretch readable.
-- - ariege-pyrenees-trout: NOT RESEARCHED in this pass.
-- - lac-du-der-pike: Only the inter-prefectoral fishing order (Marne/Haute-Marne prefecture PDFs) found; PDFs not readable here.
-- - lake-como-shad: Searched: Regione Lombardia pages give the regional licence system and per-basin "prontuari" (PDFs); no readable lake-specific closures or access detail.
-- - sardinia-dentex: NOT RESEARCHED in this pass.
-- - venice-lagoon-bass: NOT RESEARCHED in this pass.
-- - noce-river-trentino: Provincia autonoma di Trento pages found cover licences and permits generally (guest permits up to 30 days) and the Noce management plan is a PDF not readable here; no beat-level access detail.
-- - tiber-river-rome: ARPA Lazio project page covers mercury contamination in the Paglia valley (recommended fishing/consumption ban on the Paglia, a tributary); for the Tiber section studied it reports fish within health limits, with a caveat for adult predators. No advisory specific to Rome found and no access page; nothing stated rather than implying one. Worth a follow-up with the Lazio region/ASL.
-- - argentario-amberjack: NOT RESEARCHED in this pass.
-- - lake-maggiore-trout: Same as lake-como-shad (Lombardy prontuari are PDFs); the Piedmont side and the Swiss permit point were not searched.
-- - rio-sella-salmon: Asturias government sites (pescafluvial.asturias.es, sede.asturias.es) refused connections or showed an error page in both WebFetch and the browser. Search results indicate cotos are allocated by annual sorteo (application opens around September, draw in October), which conflicts with the existing "allocated by daily draw" wording, but this was not confirmed on a page I could read, so neither record nor correction is written. Follow-up: verify on an Asturias page and fix the regulations line.
-- - galicia-rias-bass: Xunta pages found cover only the recreational-fishing licence (already in existing regulations); nothing place-specific to the Rias Baixas access.
-- - pyrenees-noguera-trout: Generalitat fishing-zone pages found but the zone maps are PDFs not readable here; only general classification-based permit information.
-- - embalse-orellana-bass: HELD: verified on a Junta de Extremadura page (extremambiente.juntaex.es, "Limitaciones a la pesca desde orilla por motivos ambientales en Extremadura") that loads only over http. It states shore fishing is prohibited all year at three named places on the Embalse de Orellana (peninsulas that become islands in the Zonas de Uso Limitado; the north-west slope of Cerro de Cogolludo from the Cogolludo bridge to 1,000 m upstream; the mouth of the Arroyo de las Valsecas) under the Zona de Interes Regional management plan (Orden of 28 December 2012). Content rule 2 and check-access-migration.mjs require an https sourceUrl, and https did not load, so the record was not written. Sean can decide whether to accept the http URL or wait for an https page.
-- - balearic-dentex: Govern balear marine-reserve rules found apply to named reserves (ses Bledes, Vedra, Toro and Malgrats, east Mallorca), not to Mallorca generally; spot location not matched to a reserve.
-- - rio-duero-barbel: Junta de Castilla y Leon and Confederacion Hidrografica del Duero pages found are general (floating-device rules, navigation declarations), not specific to the barbel stretch.
-- - femunden-grayling: NOT RESEARCHED in this pass.
-- - senja-halibut: NOT RESEARCHED in this pass.
-- - saltstraumen-coalfish: Statsforvalteren Nordland documents concern the marine protected area plan for Saltstraumen (recommended vs discouraged fishing zones, lost hooks), found only as consultation PDFs; the adopted plan was not located on a readable page. Follow-up possible.
-- - glomma-grayling: NOT RESEARCHED in this pass.
-- - gaula-river-salmon: Statsforvalteren i Trondelag pages found cover the region-wide salmon regime (fiskeravgift, evaluation of fishing pressure); nothing specific to Gaula access. A region-wide rule repeated across rivers would be filler.
-- - namsen-river-salmon: Same as gaula-river-salmon.
-- - hjalmaren-zander: NOT RESEARCHED in this pass.
-- - malaren-pike: NOT RESEARCHED in this pass.
-- - asnen-pike: Naturvardsverket page for the national-park regulations (NFS 2018:1) is only a landing page linking a PDF; Lansstyrelsen Kronoberg pages found give general park information. Fishing/landing rules not readable on an HTML page.
-- - turku-archipelago-pike: NOT RESEARCHED in this pass.
-- - helsinki-coastal-zander: NOT RESEARCHED in this pass.
-- - kuusinkijoki-trout: Metsahallitus permit areas for the Oulanka region found, but no page specific to Kuusinkijoki could be located in this pass; the Oulankajoki page is a different river.
-- - paijanne-lake: NOT RESEARCHED in this pass.
--

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"Mecklenburg-Vorpommern''s fisheries authority states that angling in its coastal waters (the Bodden, Haffe, Peenestrom, Achterwasser and the Baltic Sea within German territorial waters) always needs three personal documents: a Fischereischein, an Angelerlaubnis and proof of payment of the state fishing fee. There are no free angling waters in MV. Visitors can obtain a temporary Touristenfischereischein valid for up to 28 days. Check the LALLF M-V for how to obtain each document before you travel.","sourceUrl":"https://www.lallf.de/fischerei/angelfischerei/fischereidokumente-allg/"}'::jsonb, regulations = '["Baltic coastal fishing in Mecklenburg-Vorpommern requires a Fischereischein, an Angelerlaubnis (coastal fishing permit) and proof of payment of the state Fischereiabgabe","Sea trout have a minimum size and a closed season for coloured fish","Cod bag limits are set annually by EU rules — check before keeping fish"]'::jsonb, updated_at = now() WHERE slug = 'ruegen-baltic-sea-trout';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"The Schleswig-Holstein Wadden Sea National Park authority states that angling in the coastal strip is generally possible, except in breeding and resting sites in salt marshes that are marked on site. Angling from boats is possible almost everywhere in the park, but is prohibited in the usage-free zone south of the Hindenburgdamm. Check the national-park rules and signage before fishing.","sourceUrl":"https://www.nationalpark-wattenmeer.de/wissensbeitrag/sport-und-freizeitfischerei/"}'::jsonb, updated_at = now() WHERE slug = 'sylt-north-sea';

UPDATE public.spots SET access = '{"boat":true,"notes":"Recreational bluefin tuna fishing in the Mediterranean from a French-flagged or EU-registered recreational or charter vessel requires an annual authorisation from the regional maritime authority (DIRM), applied for with the CERFA form published by the Ministry of the Sea. Vessels flying the flag of a non-EU state may not fish bluefin tuna recreationally. A tuna that is retained must be tagged immediately with the marking ring supplied, and each landing must be declared to FranceAgriMer within 48 hours. Check the Ministry of the Sea and current French and ICCAT rules before targeting tuna.","sourceUrl":"https://www.mer.gouv.fr/pratiquer-la-peche-de-loisir-au-thon-rouge"}'::jsonb, updated_at = now() WHERE slug = 'sete-mediterranean-tuna';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"The Ministry of the Sea advises shore anglers to respect minimum sizes and closed seasons, to leave no waste on the foreshore and to tell someone where they are going before setting out. Recreational fishers aged 16 and over who target designated sensitive species, including sea bass in the Channel and Bay of Biscay zones, must register each year through the RecFishing app and declare catches daily. Catches are marked by removing the lower part of the tail fin. Check the Ministry''s shellfish sanitary zone maps before gathering shellfish, and check tide times carefully before fishing rock marks.","sourceUrl":"https://www.mer.gouv.fr/peche-de-loisir-en-mer"}'::jsonb, regulations = '["No licence required for recreational sea fishing","Recreational anglers aged 16 and over targeting sea bass in the Channel must register annually through the RecFishing app and declare their catches; catches must be marked by removing the lower part of the tail fin — check the Ministry of the Sea before fishing","Bass minimum size and bag limits apply","Tides here are among the largest in Europe — check times carefully before fishing rock marks"]'::jsonb, updated_at = now() WHERE slug = 'normandy-bass-cotentin';

UPDATE public.spots SET access = '{"boat":true,"notes":"The Egadi Islands Marine Protected Area is zoned: A (integral reserve, western Marettimo and the Maraone islet), B (general reserve around the Faraglione of Favignana, west Levanzo and parts of Marettimo), C (partial reserve: all of Favignana, and the east sides of Levanzo and Marettimo) and D (the protection zone between the islands). The MPA lists sport fishing for zones B and C only, under authorisation from the MPA management body, and spearfishing is prohibited throughout the MPA. Check the MPA''s current zoning map and authorisation procedure before fishing.","sourceUrl":"https://www.ampisoleegadi.it/index.php/zonazione/"}'::jsonb, updated_at = now() WHERE slug = 'sicily-bluefin-tuna';

UPDATE public.spots SET access = '{"boat":true,"notes":"The Canary Islands government issues recreational sea-fishing licences in three classes: class 1 for surface trolling from a vessel, class 2 for spearfishing and class 3 for surface fishing from land or from a vessel without trolling. Licences are valid for three years and are applied for through the regional electronic office. Marlins, tunas, swordfish and hake are species under differentiated protection that need a separate authorisation from Spain''s national fisheries ministry. Check the Canary Islands government and the ministry for current rules before targeting them.","sourceUrl":"https://www.gobiernodecanarias.org/pesca/temas/pesca_recreativa/licencias.html"}'::jsonb, updated_at = now() WHERE slug = 'canary-islands-marlin';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"If fishing inside the Cap de Creus Natural Park (Girona coast), the park authority requires a special park permit, obtained after environmental and fishing training, in addition to the general recreational fishing licence; permit holders must report catches daily and mark fish caught. Only catch-and-release fishing is allowed in the coves of Murtra, Caials and Tamariua, and fishing is banned in the S''Encalladora Integral Natural Reserve. Check the park''s current zoning and rules before fishing.","sourceUrl":"https://parcsnaturals.gencat.cat/ca/xarxa-de-parcs/cap-creus/gaudeix-del-parc/guia-de-visita/que-shi-pot-fer/activitats-a-mar"}'::jsonb, regulations = '["Catalonia recreational sea fishing licence required","Catch reporting via the PescaREC app applies since March 2026","Some marine reserves along this coast are no-take and Cap de Creus Natural Park has its own fishing permit and zoning — check local zoning"]'::jsonb, updated_at = now() WHERE slug = 'costa-brava-spinning';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"HEALTH ADVICE: Mattilsynet (the Norwegian Food Safety Authority) publishes dietary advice for the Hardangerfjord/Sorfjorden area, which is contaminated with cadmium, lead, mercury, dioxins and PCB. The advice includes avoiding brosme and pollock in specified zones, pregnant and nursing women avoiding crab, lobster and stationary fish in the inner areas, and shellfish restrictions in designated zones. Read Mattilsynet''s current advice and zone descriptions before eating any catch, and confirm current Norwegian fishing rules.","sourceUrl":"https://www.mattilsynet.no/mat-og-drikke/forbrukere/unnga-fisk-og-skalldyr-fra-forurensede-havner-fjorder-og-innsjoer"}'::jsonb, updated_at = now() WHERE slug = 'hardangerfjord-sea-trout';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"HEALTH ADVICE: Mattilsynet (the Norwegian Food Safety Authority) publishes dietary advice for fish and shellfish from polluted fjords. For the inner Oslofjord (inside Drobak) it advises pregnant and nursing women and children under 5 not to eat cod fillet because of mercury, and advises the general population to avoid mussels from the inner harbour area because of PAH. Check Mattilsynet''s current advice for any fish you plan to eat, and confirm current Norwegian fishing rules.","sourceUrl":"https://www.mattilsynet.no/mat-og-drikke/forbrukere/unnga-fisk-og-skalldyr-fra-forurensede-havner-fjorder-og-innsjoer"}'::jsonb, updated_at = now() WHERE slug = 'oslofjord-sea-trout';

UPDATE public.spots SET access = '{"boat":true,"notes":"HEALTH ADVICE: the Swedish Food Agency (Livsmedelsverket) warns that wild-caught char from Lake Vattern, and wild trout, whitefish and salmon from Vattern, can contain high levels of dioxin and PCB. Children, young people and anyone who is pregnant, breastfeeding or planning a pregnancy should eat these fish at most two to three times a year; other adults can eat them about once a week. The Agency also advises not eating eel at all. Check the Food Agency''s current advice before eating your catch, and confirm current fishing rules with the county board.","sourceUrl":"https://www.livsmedelsverket.se/matvanor-halsa--miljo/kostrad/fisk-som-kan-innehalla-miljogifter/"}'::jsonb, updated_at = now() WHERE slug = 'vattern-char';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"Lansstyrelsen Vastra Gotaland states that fishing with hand-held gear in the sea is free, but from 1 January to 31 March fishing for cod is prohibited inside the trawl boundary, fishing for cod is prohibited all year in the Gullmarsfjorden protection area, and from 1 October to 31 March fishing is prohibited in all protected areas (fredningsomraden). The county board''s Svenska Fiskeregler map service shows the protected areas. Check the current rules before fishing.","sourceUrl":"https://www.lansstyrelsen.se/vastra-gotaland/djur/fiske.html"}'::jsonb, regulations = '["Rod fishing in Swedish saltwater is free and unlicensed","Cod: fishing for cod is prohibited inside the trawl boundary from 1 January to 31 March and all year in the Gullmarsfjorden protection area — check current limits before keeping any","All protected areas (fredningsomraden) are closed to fishing from 1 October to 31 March — check Svenska Fiskeregler for the map","Sea trout have minimum sizes and closed seasons near river mouths"]'::jsonb, updated_at = now() WHERE slug = 'bohuslan-coast-mackerel';

UPDATE public.spots SET access = '{"shore":true,"notes":"Lansstyrelsen Vasterbotten manages the Vindelalven between Mankeforsen and Sarngejukkes as a quota water: permits are allocated by lottery, applications are open from 1 January to 30 April, results are announced from the second half of May, and you can apply for up to five fishing days. Fly fishing with a fly rod only applies on most quota waters, catch reporting is mandatory, and the season on the Vindelalven runs from 1 July to 20 August. Children under 16 go free with a guardian. Check the county board page for the current application rules.","sourceUrl":"https://www.lansstyrelsen.se/vasterbotten/djur/fiske/fiska-i-fjallen/ansok-om-fiske-i-kvoterade-vatten.html"}'::jsonb, regulations = '["The Vindelalven between Mankeforsen and Sarngejukkes is quota-managed: a lottery permit from Lansstyrelsen Vasterbotten is required (applications 1 January to 30 April), not an ordinary fiskekort","Fly fishing with a fly rod only on most quota waters; catch reporting is mandatory","The season is short (1 July to 20 August on the Vindelalven) — check the county board for current rules and salmon regulations"]'::jsonb, updated_at = now() WHERE slug = 'vindelalven-grayling';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"Lansstyrelsen Gotland (the county administrative board) states that fishing with hand-held tackle is free along the sea coast, but permission is needed in streams and most other inland waters. Sea trout are protected from 1 September to 31 January in 25 protected areas at 34 streams, and from 2025 the protection also applies within the watercourses, not just the mouths. Pike and perch are protected in the coastal waters out to four nautical miles around the whole of Gotland from 1 March to 31 May. Check the county board''s current rules and protected-area maps before fishing.","sourceUrl":"https://www.lansstyrelsen.se/gotland/djur/fiske.html"}'::jsonb, regulations = '["Rod fishing in saltwater is free and needs no licence","Sea trout minimum size applies and coloured fish must be released","Sea trout are protected from 1 September to 31 January in protected areas at Gotland streams, including within the watercourses themselves — check the county board map","Pike and perch are protected in Gotland coastal waters (out to 4 nautical miles) from 1 March to 31 May"]'::jsonb, updated_at = now() WHERE slug = 'gotland-sea-trout';

UPDATE public.spots SET access = '{"boat":true,"notes":"Metsahallitus issues the angling permit for the state waters of Lake Inarijarvi and Lake Nitsijarvi through its Eraluvat permit service. The permit is specific to the boating party, so one valid permit covers one boat, and the number of permits is limited. The state fisheries management fee also applies to lure anglers aged 18 to 69, while hook-and-line and ice fishing with one rod are free. The lake has more than 3,000 islands and many shallow areas. Check the Inari fisheries area rules and the permit terms before fishing.","sourceUrl":"https://www.eraluvat.fi/en/areas/1504-inarijarvi-1185/products"}'::jsonb, updated_at = now() WHERE slug = 'inari-lake-trout';

UPDATE public.spots SET access = '{"shore":true,"notes":"At Langinkoski (the lowest rapids of the Langinkoski branch of the Kymijoki, inside the Langinkoski nature reserve near Kotka city centre) Metsahallitus allows fly fishing only with an angling permit, and no more than eight people may fish at once. Native fish with an intact adipose fin may not be kept, to protect the salmon and sea trout runs. The season runs from 1 January to 30 September and from 1 December to 31 December. The state fisheries management fee also applies to anglers aged 18 to 69. Check the permit terms on Eraluvat, and other Kymijoki sections have different rules.","sourceUrl":"https://www.eraluvat.fi/en/fishing/fishing-permits/angling-permit/alueet/langinkoski.html"}'::jsonb, updated_at = now() WHERE slug = 'kymijoki-river';

UPDATE public.spots SET access = '{"shore":true,"notes":"Metsahallitus manages fishing in the Ruunaa rapids as permit area 7525, running from Paasikoski to below Siikakoski and including Murroojarvi and Kattilajarvi. A rod-fishing permit and the state fisheries management fee are required for most anglers. Wading is prohibited from 1 September to 31 May, and fishing is banned in the Paasikoski to Mutikaisenkari section from 1 September to 30 November. Angling and jigging are not allowed in flowing water but are allowed in still water with a permit. Kattilakoski is a reserved rapid booked for groups. Check the permit terms on Eraluvat for current rules.","sourceUrl":"https://www.eraluvat.fi/kohteet/7525-ruunaan-kosket-527"}'::jsonb, updated_at = now() WHERE slug = 'ruunaa-rapids';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"The City of Imatra divides the Vuoksi fishing waters into the Vuoksi itself (excluding Mellonlahti) and Mellonlahti, each with its own permit. On the Vuoksi, fly fishing, spinning and trolling are allowed, bait fishing and ice fishing need no Vuoksi permit, and motor trolling is limited to the stretch between Kyyronkoski and the border zone. All fishing is prohibited from 15 October to 15 November between the railway bridge and the river mouth, and grayling are protected from 1 April to 31 May. Check the City of Imatra''s current permit terms before fishing.","sourceUrl":"https://www.imatra.fi/asuminen-ja-ymparisto/virkistysalueet/kalastus/vuoksen-kalastusalueet-ja-lupaehdot"}'::jsonb, updated_at = now() WHERE slug = 'vuoksi-river-trout';

