-- Verified access details — Vänern, Stockholm Archipelago, Mörrum, Paraná,
-- Pantanal, Nikkō (2026-07-29)
--
-- Sources: Havs- och vattenmyndigheten, Länsstyrelsen Stockholm,
-- Livsmedelsverket, Sveaskog (Mörrums Kronolaxfiske), the Corrientes Ministerio
-- de Turismo / Dirección de Recursos Naturales, IMASUL and the Assembleia
-- Legislativa de Mato Grosso do Sul, and the Nikkō fishery operator.
--
-- Health advisories found and recorded for all three Swedish waters
-- (Livsmedelsverket dioxin/PCB advice for Vänern salmon and whitefish and for
-- Baltic salmon; mercury advice covering pike). NOT recorded for Nikkō: Tochigi
-- Prefecture does publish post-2011 shipping restrictions and their lifting,
-- but its page does not name Lake Yunoko or the Yugawa, and a restriction on
-- Lake Chūzenji brown trout must not be extended to a different water.

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "NO PERMIT NEEDED: Vänern is one of Sweden''s five great lakes where fishing with handheld tackle is free — no fiskekort. The same right covers the sea coast and inflowing watercourses up to the first definitive migration barrier. Note that allemansrätten, the right of public access, does not itself extend to fishing; this is a separate statutory right. CHECK THE ADIPOSE FIN: only fin-clipped (fettfeneklippt) salmon and trout may be kept from Vänern. Taking unclipped fish is prohibited year-round, so look before you decide — an unclipped fish goes back whatever its size. TROLLING: in public water a maximum of ten baits per boat when trolling, dörjing or utter-fishing, and trolling behind a motorised boat is prohibited inside certain protected areas, including around the Gullspångsälven. Länsstyrelsen publishes the Vänern rules and the fredningsområden maps, and the national portal is svenskafiskeregler.lansstyrelsen.se. HEALTH ADVICE: Livsmedelsverket, the Swedish Food Agency, warns that wild salmon from Vänern and whitefish (sik) from Vänern can carry high levels of dioxins and PCBs. Children, young people, pregnant and breastfeeding women and anyone who may want children in future are advised to eat these fish no more than two to three times a year; everyone else no more than once a week. Check current rules before fishing.", "sourceUrl": "https://www.havochvatten.se/fiske-och-handel/regler-och-lagar/fiskeregler-for-fritidsfiske.html"}'::jsonb, updated_at = now() WHERE slug = 'vanern-salmon';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "NO PERMIT NEEDED: fishing with handheld tackle is free along the whole Swedish coast, the archipelago included, and needs no fiskekort. Allemansrätten does not itself cover fishing — this is a separate right, and it does not override local restrictions. CLOSED AREAS ARE THE REAL CONSTRAINT HERE: Länsstyrelsen Stockholm has designated 62 bays in the archipelago where fishing is banned in spring to protect spawning fish, nine of which are closed all year, plus 14 protected areas at river mouths closed in autumn while sea trout run upstream. Many are exactly the shallow, weedy bays a pike angler would head for — the county has registered some 300 pike spawning sites in the archipelago. Länsstyrelsen publishes a map of the protected areas as a downloadable PDF and the rules at svenskafiskeregler.lansstyrelsen.se, and states plainly that the angler is responsible for finding out which rules apply before fishing. Selling a catch taken from the sea requires a commercial licence. HEALTH ADVICE: Livsmedelsverket lists pike, along with perch, zander and burbot, among the freshwater fish that can carry high mercury levels, and advises anyone pregnant, breastfeeding or trying to conceive to eat them no more than two to three times a year, because mercury crosses the placenta and passes into breast milk. Levels vary a lot between waters, and the county board and municipality hold the local figures. Check current rules before fishing.", "sourceUrl": "https://www.lansstyrelsen.se/stockholm/djur/fiske.html"}'::jsonb, updated_at = now() WHERE slug = 'stockholm-archipelago-pike';

UPDATE public.spots SET access = '{"shore": true, "boat": false, "parking": "Laxens Hus is the reception and administrative centre for the fishery — permits, catch registration, a weighing station and rule enquiries are all handled there.", "facilities": ["Laxens Hus reception", "Catch registration and weighing station", "Numbered beats"], "notes": "This is a managed beat fishery run by Sveaskog as Mörrums Kronolaxfiske, not open water. SEASON AND HOURS: 1 March to 30 September. On opening day, 1 March, fishing runs 09:00–17:00; on other days 05:00–02:00; on the final day, 30 September, 05:00–00:00. PERMIT: personal and non-transferable, bought at the Laxens Hus reception or online at morrum.com, and you must carry photo ID for inspection. BEATS: the water is divided into numbered pools, 1–16 and 17–32, with additional zoning restrictions applied between 15 and 31 May. METHOD: fly and spinning rods only, one rod per person. Spinning with drifting weights and casting floats is allowed; casting upstream is prohibited, and so is sonar or any electronic fish-locating equipment. REGISTRATION: every salmon must be registered whether it is killed or released, regardless of length, through the website or at reception on the day of capture. Strict personal, daily and season-wide kill quotas apply, and once the season-wide total is reached nobody may kill another fish that year — check the current figures before you book. HEALTH ADVICE: Livsmedelsverket advises that wild salmon from the Baltic and the rivers running into it can carry high levels of dioxins and PCBs, and that children, young people, pregnant and breastfeeding women and anyone who may want children in future should eat such fish no more than two to three times a year, others no more than once a week. Check current rules before fishing.", "sourceUrl": "https://www.sveaskog.se/en/morrum/sportfiske/fishing-rules/"}'::jsonb, updated_at = now() WHERE slug = 'morrum-river-salmon';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "CATCH AND RELEASE ONLY: the Dirección de Recursos Naturales, under the Corrientes Ministry of Tourism, permits sport fishing throughout the province solely as pesca y devolución. Extractive fishing of dorado is prohibited outright — it may be fished only catch-and-release, and only with tackle suited to that. Barbless hooks (anzuelos sin rebaba) are required. DAYS OF THE WEEK: on the stretch of the Paraná from the confluence zone down to the mouth of the Arroyo Ambrosio — which takes in Paso de la Patria — sport fishing has been permitted Thursday to Monday, with Tuesday and Wednesday closed. That restriction is set by provincial disposition and has been varied before, so confirm the current one rather than assuming. LICENCE: since the platform came in, Corrientes sport fishing licences are sold only electronically, through www.licenciasrecursosnaturales.gob.ar. The site works in several languages and takes a couple of minutes; tourism operators reselling licences must first register as providers. Fines can also be paid through it. Infractions are dealt with administratively and can mean a fine or suspension of an operator''s licence. Check the current reglamento before fishing.", "sourceUrl": "https://turismo.corrientes.gob.ar/noticia/desde-el-primero-de-enero-regira-la-plataforma-digital-de-gestion-para-la-compra-de-licencias-de-pesca"}'::jsonb, updated_at = now() WHERE slug = 'parana-river-dorado';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "notes": "DOURADO IS CATCH-AND-RELEASE ONLY, BY STATE LAW: Mato Grosso do Sul prohibits the capture, loading, transport, sale, processing and industrialisation of dourado. The ban has been extended to 31 March 2027, and pesque e solte — catch and release — is expressly excepted from it, along with consumption by professional and riverside fishers and fish raised in captivity. The Legislative Assembly requires technical, scientific and economic studies by 28 February 2027, presented at a public hearing, before the position is reviewed again. Anyone travelling to the Pantanal to fish dourado should plan on releasing every one. LICENCE: amateur anglers need the Carteira de Pescador Amador, issued by IMASUL at pescaamadora.imasul.ms.gov.br or through the MS Digital app. Authorisations come as annual, quarterly or monthly, and separately for boat-based, shore-based and catch-and-release fishing. CLOSED SEASON: the piracema defeso closes fishing while the shoals run upstream to spawn; the dates are set each year, so check before booking. CATCH-AND-RELEASE-ONLY RIVERS: under CECA deliberations 006/2000 and 003/2000, the Rio Perdido, the Rio Abobral and Rio Vermelho in the Pantanal, and the Rio Negro at Aquidauana are catch-and-release only, to be fished with barbless hooks and the fish returned to the water quickly. PROHIBITED GEAR: nets, cast nets, branch lines, longlines, fixed enclosures, traps, gaffs, grappling and treble snagging hooks, harpoons, arrows, and explosive or toxic substances. IMASUL and the Environmental Police publish a Cartilha do Pescador covering the detail. Check current rules before fishing.", "sourceUrl": "https://www.imasul.ms.gov.br/aberta-temporada-de-pesca-imasul-esclarece-regras-vigentes-em-ms-e-ensina-como-emitir-a-carteira-digital/"}'::jsonb, updated_at = now() WHERE slug = 'pantanal-dorado';

UPDATE public.spots SET access = '{"shore": true, "boat": true, "parking": "The fishery operates from roadside offices and rest houses in Okunikkō rather than a single car park — permits, rentals and boat bookings are all handled at those counters.", "facilities": ["Permit offices and rest house", "Rod and reel hire", "Bait and tackle for sale", "Rowing boats by reservation", "Catch badge issue"], "notes": "PERMIT REQUIRED: buy before you fish, from the Nikkō fishing office (0288-62-2524), the Chūzenji fishing association (0288-55-0150) or the rest house (0288-62-8611). Day and half-day permits are sold, and rods and reels can be hired on site. Boats on Lake Yunoko are booked through the rest house. SEASON AND HOURS: Lake Yunoko fishes from 2 May to 30 September, from first light until 17:00. The Yugawa, the river running out of the lake, opens on 1 May and fishes 06:30 to 17:00. METHODS: the operator caters for fly, lure and bait fishing alike — it sells bait and hires both bait and lure outfits. Some English-language guides describe the lake as artificial-lure-only, which does not match what the fishery itself publishes. CATCH BADGES: anglers who take fish collect catch badges from the fishery office during its opening hours, and the fishery runs a catch-and-release ranking through the season. A daily catch limit applies — check the current figure when you buy the permit. The lake sits inside Nikkō National Park in the Okunikkō wetlands, so general park rules on litter, fires and staying to the paths apply on top of the fishing rules. Check current rules before fishing.", "sourceUrl": "https://www.naisuimen.or.jp/nikko/fishing/fee.html"}'::jsonb, updated_at = now() WHERE slug = 'nikko-yunoko-trout';
