-- Verified access details — batch 12
--
-- 7 spot(s) with records, 39 skipped. Every sourceUrl is an official
-- government, park-authority, council or fisheries-body page (CLAUDE.md content rules 1-3).
-- Apply by hand in the SQL Editor, then rebuild (migration first, then build).
--
-- sterkfontein-dam: Free State DESTEA (Department of Economic, Small Business Development, Tourism and Environmental Affairs, the provincial reserve manager) Sterkfontein Dam Nature Reserve page, read via WebFetch: about 23 km from Harrismith on the R74; slipways and boathouses; camping with ablution facilities; no shops; gate and office hours; angling among activities. The page says nothing about angling permits or rules, so none are stated. Chalet refurbishment notice deliberately left out as transient.
--
-- nahuel-huapi-trout: Parque Nacional Nahuel Huapi (national park administration) "Pesca Deportiva" page, read via WebFetch: season 1 November to 1 May inclusive; fishing permits are mandatory and personal, sold by day, week or season at local fishing shops and retailers; spinning, trolling and fly casting authorised; independent fishing or authorised park guides; full rules in the national regulation site reglamentodepesca.org.ar. The page gives no parking, release or equipment detail, so none is stated (search snippets with parking and release rules were not on this page). Existing regulations consistent ("season dates set annually") and now carry the stated dates.
--
-- loreto-yellowtail: CONANP (Mexico's national protected-areas commission) news page on the updated management programme of Parque Nacional Bahia de Loreto, read via WebFetch: the no-fishing area grew from 108.4 to 6,219.3 hectares, low-selectivity fishing gear is restricted, and jet skis/motorised water vehicles are prohibited. The page does not spell out sport-fishing rules or zoning, so none are stated; the record tells anglers to check the zoning. The spot is written as "if fishing inside the park" since the spot location was not matched to the park boundary.
--
-- lake-biwa-bass: Shiga Prefecture page on the Invasive Alien Species Act and the ban on releasing invasive fish, read via WebFetch (Japanese): the Shiga Prefecture Lake Biwa Leisure Use Appropriateness Ordinance prohibits releasing black bass and bluegill; caught fish should be taken to the designated recovery boxes or holding pens around the lake; transporting them live within Lake Biwa (including harbours) to a recovery box or keeping them alive in a bucket while fishing is allowed, but taking live fish out of the lake area is a violation. The page itself notes the national Act does not directly ban catch-and-release and leaves release bans to local governments. CONTRADICTION FIXED: existing regulations said "Transporting live bass is illegal"; too broad, so reworded.
--
-- hokkaido-shiretoko-salmon: Hokkaido Prefecture fisheries management page "Fishing rules and manners", read via WebFetch (Japanese): dedicated salmon/trout fishing rules and a list of zones near river mouths where salmon and trout may not be taken, regional rule maps and warnings on illegal gear. Existing regulations already say river salmon fishing is prohibited; the addition is the prohibited zones near river mouths (prefecture list). The bear-related request to keep out of Horobetsu River estuary areas came from the Shiretoko Foundation (not a government body) and is not used.
--
-- okinawa-gt: Okinawa Prefecture FAQ page on harvesting marine animals and plants (Japanese), read via WebFetch: ordinary (recreational) people may use rod and hand-line fishing (no lights), landing nets, cast nets from shore only, hand-held spears without propulsion, hand capture and trolling; spearfishing with mechanical propulsion is banned; fragments of coral and live rock may only be taken with permission; harvesting protected coral species is forbidden; some areas and periods are closed to harvesting and the Water Products Division (098-866-2300) publishes a pamphlet. Existing regulations (no licence, reef protection, typhoon season) consistent. The Yaeyama spawning closure seen in a search result was not on this page and is NOT stated (the spot is not tied to Yaeyama).
--
-- volga-delta-catfish: Rosrybolovstvo (Federal Agency for Fisheries), Volga-Caspian territorial administration, "Pamyatka dlya rybolova-lyubitelya" for Astrakhan Oblast, read via WebFetch (Russian): amateur fishing on public water bodies is free and without charge under the Volga-Caspian fishing rules; fishing is prohibited 16 May-20 June across the region (except within settlements); sturgeon species are prohibited; prohibited zones include the Volga pre-mouth protected area, sturgeon and fish spawning grounds, hydro-facility safety zones and registered shipping channels; nets, traps and similar gear banned. The page's species list was machine-summarised inconsistently (zander appeared in one listing), so NO species other than sturgeon is stated, and the 2026 roach/vobla bans are not restated. CONTRADICTION/GAP FIXED: existing regulations did not mention the regional closed period or the prohibited zones.
--
-- Not included this batch:
-- - orange-river-yellowfish: NOT RESEARCHED in this pass.
-- - vaal-river-yellowfish: Searched: only Department of Water and Sanitation planning documents (Vaal Dam resource management plan) and a Gauteng fishing-permit service page found; no access page for the yellowfish stretches.
-- - transkei-wild-coast: Searched: ECPTA reserve booking pages and the national DFFE recreational permit page only; no reserve-specific fishing rules found.
-- - durban-deep-sea: Searched: eThekwini pier-fishing notices (fishing allowed only at certain piers; not allowed next to ski-boat launch sites at certain hours) and TNPA port pages; nothing on launch sites for offshore anglers confirmed. The municipal pier notice is not specific to deep-sea launching.
-- - dullstroom-trout: Previously skipped in batch 9: only tourism and lodge sources, no official MTPA access page.
-- - west-coast-snoek: Searched: only the national DFFE recreational permit system (already common to all South African marine spots) and West Coast rock lobster conditions; nothing specific to the snoek fishery access.
-- - jozini-tigerfish: Ezemvelo KZN Wildlife (provincial authority) pages found only confirm Phongolo Nature Reserve is known for tigerfish; the reserve page errored in both WebFetch and the browser, and no official page on permits or launching was readable.
-- - rio-limay-trout: Neuquen government sites (cazaypesca.neuquen.gob.ar, w2.neuquen.gov.ar) failed DNS in WebFetch and showed an error page in the browser. Search summaries suggest the Limay opens on 1 November, which may conflict with the existing "mid-November to mid-April" season line; NOT verified, so neither record nor correction is written. Follow-up worth doing.
-- - rio-chimehuin: Same Neuquen sites unreachable. Search summaries mention an additional "preferential zone" permit for Zone I (Boca) of the Chimehuin and Correntoso; NOT verified on a readable page.
-- - rio-gallegos-sea-trout: Searched: Santa Cruz government news and permit-system pages (permit covers rivers and lakes; coastal rod fishing free; natural bait and multiple hooks prohibited) but no Rio Gallegos-specific access page; existing regulations already say access is through estancias and lodges.
-- - mar-del-plata-offshore: Searched: Buenos Aires Province fisheries directorate pages say a provincial sport-fishing licence is required and mention both continental and marine/estuarine waters, but do not say whether it applies to sea shore or boat fishing at Mar del Plata; the regulation text is on a Google Drive link. The existing line "No licence is required for sea fishing in most Argentine coastal provinces" may therefore be wrong for Buenos Aires Province but is NOT verified either way. Follow-up worth doing.
-- - peninsula-valdes-shore: Searched: Chubut government pages found cover the Frente Valdes marine-protected-area proposal and artisanal fishing; nothing readable on recreational shore-fishing rules.
-- - embalse-rio-tercero: Cordoba environment-ministry pages (ambiente.cba.gov.ar, prensa.cba.gov.ar) are geo-blocked from this environment (CloudFront 403) and were not read. Search summaries mention a new fishing regulation (Resolution 250) with a year-round ban on night fishing, a spring closure of shore and boat fishing in coastal sectors of Cordoba lakes from the third weekend of September to the third weekend of December, and a total ban on dorado in the Tercero basin; NOT VERIFIED, so nothing is written. High-value follow-up for someone who can open the site.
-- - agua-boa-peacock-bass: Lodge-access model (CLAUDE.md group); not researched in this pass.
-- - rio-xingu-payara: NOT RESEARCHED in this pass.
-- - cabo-frio-offshore: ICMBio page for the Arraial do Cabo marine extractive reserve read: reserve covers a three-mile strip off Arraial do Cabo and motorboats/jet skis are regulated by protocol, but the page does not state sport-fishing rules; the sport-fishing restriction appeared only in a search snippet of an ICMBio portaria and the spot is not shown to lie inside the reserve.
-- - vitoria-marlin: Searched: national Ministry of Fisheries licence-for-amateur-fishing information only (applies to all Brazilian spots); nothing place-specific.
-- - rio-sao-francisco: NOT RESEARCHED in this pass.
-- - ilhabela-sao-paulo: Searched: Sao Paulo state environment/fisheries documents (Ilhabela state park and the marine protection area management plan) are long PDFs; no readable angler rules.
-- - rio-araguaia: Searched: ICMBio pages on the Araguaia National Park found; no fishing-rule page readable in this pass, and the Ilha do Bananal is partly Indigenous land under Funai.
-- - lagoa-dos-patos: Searched: IBAMA/MPA pages found concern commercial closures (shrimp defeso) and enforcement operations; no health advisory or recreational access page found.
-- - isla-mujeres-sailfish: Searched: CONANP pages for the Costa Occidental de Isla Mujeres national park and CONAPESCA sport-fishing permit and billfish pages (national rules); park fishing rules are in PDFs not readable here.
-- - lake-el-salto-bass: NOT RESEARCHED in this pass.
-- - lake-baccarac-bass: NOT RESEARCHED in this pass.
-- - puerto-vallarta-marlin: CONANP page for Islas Marietas National Park read: it lists boat tours, wildlife viewing, snorkelling and diving and says nothing about fishing; a search snippet claimed fishing is prohibited there but the page itself did not confirm it.
-- - magdalena-bay-tuna: Searched: Baja California Sur government sport-fishing permit pages (permit required for boat and underwater sport fishing) only; nothing on Bahia Magdalena access or rules.
-- - campeche-tarpon: NOT RESEARCHED in this pass.
-- - nagara-river-ayu: Gifu Prefecture pages found cover the ayu heritage programme and the fishery cooperative regulation is a PDF; the cooperative's rules are already in the existing regulations. No readable official access page.
-- - izu-peninsula-offshore: Searched: Shizuoka Prefecture and police pages on lifejackets and rock-fishing safety, already reflected in the existing regulations.
-- - kushiro-marsh-trout: Kushiro Wetlands National Park (Ministry of the Environment) pages found cover zoning generally; the only angling rules found were the Hokkaido-wide salmon and trout rules already used for the Shiretoko spot and already in the existing regulations.
-- - kurobe-river-iwana: MLIT Kurobe River Office pages on dam-discharge warnings and angling safety were found but the angler page came back garbled in WebFetch; dam-release danger is already in the existing regulations.
-- - ariake-sea-flats: Searched: Japan Coast Guard Miike pages on tidal-flat danger and prefecture angling-rules pages; existing regulations already cover the tide hazard and fishing-rights areas.
-- - lake-baikal-omul: NOT RESEARCHED in this pass.
-- - ponoi-river: Lodge/camp-only access model (existing regulations already say so); ponoi river permits are held by licensed camps and no official page on it was located. CLAUDE.md marks this group as a separate "access-model" record, not researched here.
-- - lena-river-taimen: NOT RESEARCHED in this pass.
-- - black-sea-coast-russia: NOT RESEARCHED in this pass.
-- - karelia-lakes-pike: NOT RESEARCHED in this pass.
-- - lake-ladoga-salmon: NOT RESEARCHED in this pass.
-- - amur-river-kaluga: Rosrybolovstvo and Garant pages found are the Far East basin fishing rules as PDFs/long legal documents; kaluga/sturgeon prohibition is already in the existing regulations and could not be confirmed from a readable official page in this pass.
--

UPDATE public.spots SET access = '{"shore":true,"boat":true,"ramp":"Slipways and boathouses are available at the reserve","facilities":["Caravan park with ablution facilities and power points","Shoreline camping sites without electricity"],"notes":"Sterkfontein Dam Nature Reserve lies about 23 km from Harrismith on the Harrismith/Bergville road (R74). The reserve''s gate is open 06:00 to 22:00 and its office 07:30 to 16:00. There are no shops on the reserve, so bring your own provisions. DESTEA lists angling among the reserve''s activities but its page does not state permit requirements: contact the reserve on 058 622 3520 and check current Free State fishing rules before you go.","sourceUrl":"https://www.destea.gov.za/?page_id=3974"}'::jsonb, updated_at = now() WHERE slug = 'sterkfontein-dam';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"The Nahuel Huapi National Park administration states that the fishing season runs from 1 November to 1 May inclusive. Fishing permits are mandatory and personal, available by the day, the week or for the season from local fishing shops and retailers, and each permit comes with its own specific regulations. Spinning, trolling and fly casting are the authorised methods. You can fish independently or with an authorised park guide. The park directs anglers to the national fishing regulation site (reglamentodepesca.org.ar) for current rules.","sourceUrl":"https://nahuelhuapi.gov.ar/pesca-deportiva/"}'::jsonb, regulations = '["Nahuel Huapi National Park licence required — separate from the provincial licence","Park season runs from 1 November to 1 May inclusive — check the park administration for the current season and rules","Catch-and-release and barbless rules apply in much of the park"]'::jsonb, updated_at = now() WHERE slug = 'nahuel-huapi-trout';

UPDATE public.spots SET access = '{"boat":true,"notes":"If fishing inside Parque Nacional Bahia de Loreto, note that CONANP''s updated management programme enlarged the park''s no-fishing area to 6,219.3 hectares, restricts low-selectivity fishing gear and prohibits jet skis and other motorised water vehicles. Check the park''s current zoning map and CONANP and CONAPESCA rules before fishing.","sourceUrl":"https://www.gob.mx/conanp/prensa/conanp-actualiza-el-plan-de-manejo-del-parque-nacional-bahia-de-loreto?idiom=es"}'::jsonb, updated_at = now() WHERE slug = 'loreto-yellowtail';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"facilities":["Designated invasive-fish recovery boxes and holding pens around the lake"],"notes":"Shiga Prefecture''s Lake Biwa leisure ordinance prohibits releasing black bass and bluegill anywhere in the prefecture. Caught fish should be taken to the designated recovery boxes or holding pens set up around the lake. Moving them live inside the Lake Biwa area to a recovery box, or keeping them alive in a bucket while you fish, is allowed, but taking live fish out of the lake area is a violation. Check Shiga Prefecture''s current guidance on recovery-box locations before fishing.","sourceUrl":"https://www.pref.shiga.lg.jp/ippan/kankyoshizen/biwako/13517.html"}'::jsonb, regulations = '["A yugyoken permit is required for parts of the lake — check with the local cooperative","Largemouth bass is a designated invasive species in Japan; releasing it alive is prohibited in Shiga under the prefecture''s Lake Biwa ordinance","Do not transport live bass away from Lake Biwa — take caught fish to a designated recovery box or holding pen, or follow Shiga Prefecture''s disposal guidance"]'::jsonb, updated_at = now() WHERE slug = 'lake-biwa-bass';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"Hokkaido Prefecture publishes fishing rules that include a list of zones near river mouths where salmon and trout may not be taken, regional rule maps, and warnings about illegal gear and methods. Check the prefecture''s current list and the Shiretoko-area rule map before fishing for salmon from shore or boat, and follow park guidance on brown bears.","sourceUrl":"https://www.pref.hokkaido.lg.jp/sr/ggk/ggs/turi-r-m/rule-manner.html"}'::jsonb, regulations = '["No licence for sea fishing, but river salmon fishing is generally prohibited in Hokkaido","Salmon and trout may not be taken in designated zones near river mouths — check the Hokkaido Prefecture list and regional rule maps","Brown bears are present; never fish alone and follow park guidance"]'::jsonb, updated_at = now() WHERE slug = 'hokkaido-shiretoko-salmon';

UPDATE public.spots SET access = '{"shore":true,"boat":true,"notes":"Okinawa Prefecture allows recreational anglers to use rod and hand-line fishing (without lights), landing nets, cast nets from shore only, hand-held spears and trolling. Spearfishing with mechanical propulsion is banned, harvesting protected coral is forbidden, and taking coral fragments or live rock needs permission. Some areas and periods are closed to harvesting, and the prefecture''s Water Products Division (098 866 2300) publishes a pamphlet of the rules. Check the prefecture''s current rules and closed areas before fishing.","sourceUrl":"https://www.pref.okinawa.jp/shigoto/suisangyo/1011042/1011071.html"}'::jsonb, updated_at = now() WHERE slug = 'okinawa-gt';

UPDATE public.spots SET access = '{"boat":true,"notes":"Rosrybolovstvo''s Volga-Caspian administration states that amateur fishing on public water bodies in Astrakhan Oblast is free and needs no permit, but fishing is prohibited across the region from 16 May to 20 June (except within settlement boundaries). Sturgeon species are prohibited. Fishing is not allowed in the Volga pre-mouth protected area, on sturgeon and other spawning grounds, in hydro-facility safety zones or in registered shipping channels, and nets, traps and similar gear are banned. Check the current Volga-Caspian basin rules and species bans before fishing.","sourceUrl":"https://vktu.fish.gov.ru/pravila-rybolovstva/pamyatka-dlya-rybolova-lyubitelya/"}'::jsonb, regulations = '["No general recreational licence is required on public water bodies in Astrakhan Oblast","Amateur fishing is prohibited across the region from 16 May to 20 June (except within settlement boundaries), and sturgeon are strictly protected — targeting or keeping them is a serious offence","Prohibited zones include the Volga pre-mouth protected area, spawning grounds, hydro-facility safety zones and shipping channels; some delta channels are within protected reserves — check the current Volga-Caspian rules"]'::jsonb, updated_at = now() WHERE slug = 'volga-delta-catfish';

